# Advanced modeling (VLST): PR-AUC CV, early stopping, calibration, ensemble, threshold tuning

Companion to `modeling_without_time_since_stent.ipynb`. This notebook:

- Drops **`Time since stent implantation`** (same leakage rationale).
- Uses **`average_precision` (PR-AUC)** for `GridSearchCV` on LR and RF.
- Trains **CatBoost / XGBoost / LightGBM** with **validation early stopping** and a slightly wider hyperparameter search.
- **Calibrates** probabilities (sigmoid / Platt) on a held-out **calibration** slice of training data.
- **Ensembles** calibrated **Cat + XGB + RF** (and optional **TabPFN** in section **8b** + **9**): equal blend, **simplex grids** (PR-AUC / F2), **min-weight–constrained** PR, **diversity penalty** (PR − λ·max w), **K-fold mean OOF PR-AUC** on the cal slice, **no-Cat** XGB+RF lines, and **logistic stacking** on the three probabilities. With TabPFN enabled, **four-way** blends mirror that on **[Cat, XGB, RF, TabPFN]**: equal 1/4, PR / F2 grids, constrained PR, **K-fold mean OOF PR on the 4-simplex**, **diversity on the 4-simplex**, **no-Cat** optimization on the **XGB+RF+TabPFN** face, **Cat+TabPFN 50/50**, **XGB+RF+TabPFN thirds**, TabPFN-only, **PR/F2-winner + TabPFN tail** (15% and 25%), **Cat–XGB–TabPFN** / **Cat–RF–TabPFN** thirds, **XGB–TabPFN** and **RF–TabPFN** 50/50 mixes, a small **hand-set** blend (`cat_tabpfn_rf_thirds_xgb_tail`), and **4-prob stacking**. The **section 9 blend table** (and `ensemble_blend_comparison.csv`) lists **precision, recall, f1_score, accuracy**, and **`threshold_f1max_cal`** on the held-out **test** (threshold per row = F1-max on **cal**). In **section 9**, set **`ENSEMBLE_DEPLOY`**: `max_pr_cal_pool` (default) picks best cal PR-AUC in the **3-way** pool; or `nocat_f2_cal` / `stacking_lr_cal` (**deploy pool stays 3-way** so sections 10–11 behavior is unchanged).
- Chooses the **decision threshold** on the calibration slice (not 0.5): Fβ (β=2), recall at minimum precision, and optional cost.
- Evaluates once on the **frozen test set** from `preprocessing.ipynb`.

**SMOTE:** Defaults to **off** (`USE_SMOTE = False`). Synthetic oversampling often hurts PR-AUC here; keep off unless you are experimenting.

**Train/test split (see markdown at end):** Changing `test_size` in `preprocessing.ipynb` trades **training data vs. evaluation stability**; it does not reliably “improve model scores” on the same population.

## 1. Setup, load data, drop leaky column

In [1]:
import numpy as np
import pandas as pd
import os
import warnings
from sklearn.base import BaseEstimator, ClassifierMixin, clone
from sklearn.utils._tags import ClassifierTags
from sklearn.calibration import CalibratedClassifierCV
from sklearn.frozen import FrozenEstimator
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    classification_report,
    fbeta_score,
    precision_score,
    recall_score,
    roc_auc_score,
    f1_score,
    accuracy_score,
)
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split

from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from xgboost.callback import EarlyStopping
from lightgbm import LGBMClassifier

warnings.filterwarnings("ignore")
np.random.seed(42)

# --- Optional GPU for tree boosters (Colab: Runtime → GPU). Set VLST_USE_GPU_BOOSTERS=0 to force CPU. ---
_vlst_gpu_flag = (os.environ.get("VLST_USE_GPU_BOOSTERS", "auto") or "auto").strip().lower()
try:
    import torch

    _torch_cuda = bool(torch.cuda.is_available())
except Exception:
    _torch_cuda = False
VLST_CUDA_AVAILABLE = _torch_cuda and _vlst_gpu_flag not in ("0", "false", "off", "cpu")
CATBOOST_TASK_TYPE = "GPU" if VLST_CUDA_AVAILABLE else "CPU"
XGBOOST_DEVICE = "cuda" if VLST_CUDA_AVAILABLE else "cpu"
_lgb_gpu_env = (os.environ.get("VLST_LIGHTGBM_DEVICE") or "").strip().lower()
if _lgb_gpu_env in ("gpu", "cuda"):
    LIGHTGBM_DEVICE = "gpu"
elif _lgb_gpu_env == "cpu":
    LIGHTGBM_DEVICE = "cpu"
else:
    LIGHTGBM_DEVICE = "gpu" if VLST_CUDA_AVAILABLE else "cpu"
print(
    "Boosters:",
    "GPU" if VLST_CUDA_AVAILABLE else "CPU",
    "| CatBoost task_type=",
    CATBOOST_TASK_TYPE,
    "| XGBoost device=",
    XGBOOST_DEVICE,
    "| LightGBM device=",
    LIGHTGBM_DEVICE,
)

PROCESSED_DIR = "/kaggle/input/datasets/amirmahdidaraei/preprocessed-data"
RESULT_DIR = os.path.join("..", "..", "data", "result", "modeling_advanced")
os.makedirs(RESULT_DIR, exist_ok=True)


X_train = np.load(os.path.join(PROCESSED_DIR, "X_train.npy"))
X_test = np.load(os.path.join(PROCESSED_DIR, "X_test.npy"))
y_train = np.load(os.path.join(PROCESSED_DIR, "y_train.npy"))
y_test = np.load(os.path.join(PROCESSED_DIR, "y_test.npy"))
feature_names = pd.read_csv(os.path.join(PROCESSED_DIR, "feature_names.csv"))[
    "feature_name"
].tolist()

DROP_FEATURES = ["Time since stent implantation"]
fn = np.array(feature_names)
keep = ~np.isin(fn, DROP_FEATURES)
X_train = X_train[:, keep]
X_test = X_test[:, keep]
feature_names = fn[keep].tolist()

print(f"Train {X_train.shape}, Test {X_test.shape}, features={len(feature_names)}")
print(f"Train class 0/1: {(y_train==0).sum()}/{(y_train==1).sum()}")
print(f"Test  class 0/1: {(y_test==0).sum()}/{(y_test==1).sum()}")

Boosters: GPU | CatBoost task_type= GPU | XGBoost device= cuda | LightGBM device= gpu
Train (4148, 173), Test (1037, 173), features=173
Train class 0/1: 4074/74
Test  class 0/1: 1019/18

In [2]:
print("ping")

ping

In [3]:
!uptime

 21:18:18 up 24 min,  0 users,  load average: 0.40, 0.13, 0.08

## 1b. TabPFN API token (optional)

Run before **section 8b** if you use TabPFN. Press **Enter** to skip.

In [4]:
# import getpass

# _t = getpass.getpass("TabPFN API token [Enter to skip, not echoed]: ")
# if str(_t).strip():
    # os.environ["TABPFN_TOKEN"] = str(_t).strip()

import os

os.environ["TABPFN_TOKEN"] = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjMwZGUxYjEtMzJhMy00OWQ1LWJiZGMtNzAxYjgyZWM5MTM1IiwiZXhwIjoxODA3MzgwNzk3fQ.fPW78VeHhNf8ys9xObX7xjz8SNzw4U6qGDJTYL6NZx4"
if os.environ.get("TABPFN_TOKEN"):
    print("TABPFN_TOKEN set for this kernel.")
else:
    print("Skipped — export TABPFN_TOKEN in the shell or TabPFN will stay off in 8b.")

TABPFN_TOKEN set for this kernel.

## 1c. Cuda (optional)

Run before **section 8b** if you use TabPFN. Press **Enter** to skip.

In [5]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU only")

True
Tesla T4

## 2. Optional SMOTE (default: off)

In [6]:
from imblearn.over_sampling import SMOTE

USE_SMOTE = True

if USE_SMOTE:
    n_min = int((y_train == 1).sum())
    k = min(5, n_min - 1) if n_min > 1 else 1
    if k >= 1:
        smote = SMOTE(random_state=42, k_neighbors=k)
        X_train, y_train = smote.fit_resample(X_train, y_train)
        print("SMOTE applied:", X_train.shape, np.bincount(y_train.astype(int)))
    else:
        print("SMOTE skipped: too few minority samples.")
else:
    print("SMOTE off (recommended here based on your PR-AUC experiment).")

SMOTE applied: (8148, 173) [4074 4074]

## 3. Three-way stratified split inside training

- **fit**: model fitting (and LR/RF CV uses full `X_train` below; boosters use `X_fit`).
- **early_stop**: monitoring iterations for gradient boosting.
- **cal / threshold**: probability calibration + threshold scan (no peeking at `X_test`).

In [7]:
def three_way_stratified_split(X, y, frac_cal=0.15, frac_es=0.15, random_state=42):
    """Approximately (1 - frac_cal - frac_es) / fit, frac_es / early stop, frac_cal / calibrator."""
    X_rem, X_cal, y_rem, y_cal = train_test_split(
        X, y, test_size=frac_cal, stratify=y, random_state=random_state
    )
    es_of_rem = frac_es / (1.0 - frac_cal)
    X_fit, X_es, y_fit, y_es = train_test_split(
        X_rem, y_rem, test_size=es_of_rem, stratify=y_rem, random_state=random_state + 1
    )
    return X_fit, X_es, X_cal, y_fit, y_es, y_cal


X_fit, X_es, X_cal, y_fit, y_es, y_cal = three_way_stratified_split(
    X_train, y_train, frac_cal=0.15, frac_es=0.15, random_state=42
)
print(
    "fit:", X_fit.shape[0],
    "early_stop:", X_es.shape[0],
    "calibration/threshold:", X_cal.shape[0],
)

fit: 5702 early_stop: 1223 calibration/threshold: 1223

## 4. CatBoost wrapper + helpers

In [8]:
class CatBoostClassifierWrapper(ClassifierMixin, BaseEstimator):
    def __init__(self, **kwargs):
        self.catboost_ = CatBoostClassifier(**kwargs)

    def get_params(self, deep=True):
        return self.catboost_.get_params(deep=deep)

    def set_params(self, **params):
        self.catboost_.set_params(**params)
        return self

    def __sklearn_tags__(self):
        # Always report as classifier (sklearn is_classifier / calibration).
        tags = BaseEstimator.__sklearn_tags__(self)
        tags.estimator_type = "classifier"
        tags.classifier_tags = ClassifierTags()
        tags.target_tags.required = True
        return tags

    def fit(self, X, y, **fit_params):
        X = np.asarray(X)
        y = np.asarray(y)
        self.catboost_.fit(X, y, **fit_params)
        self.classes_ = np.unique(y)
        self.n_features_in_ = X.shape[1]
        return self

    def predict(self, X):
        return self.catboost_.predict(X)

    def predict_proba(self, X):
        return self.catboost_.predict_proba(X)


scale_pos_weight = (y_train == 0).sum() / max(int((y_train == 1).sum()), 1)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
SCORING_AP = "average_precision"

## 5. Logistic regression & random forest — `GridSearchCV` with PR-AUC

In [9]:
param_grid_lr = {
    "C": [0.01, 0.1, 1.0, 10.0],
    "penalty": ["l2", "l1"],
    "solver": ["lbfgs", "liblinear"],
    "max_iter": [2000],
}
grid_lr = GridSearchCV(
    LogisticRegression(class_weight="balanced", random_state=42),
    param_grid_lr,
    scoring=SCORING_AP,
    cv=cv,
    n_jobs=-1,
    refit=True,
)
grid_lr.fit(X_train, y_train)
best_lr = grid_lr.best_estimator_
print("LR best params:", grid_lr.best_params_)
print("LR best CV average_precision:", round(grid_lr.best_score_, 4))

/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py:1249: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

LR best params: {'C': 1.0, 'max_iter': 2000, 'penalty': 'l1', 'solver': 'liblinear'}
LR best CV average_precision: 0.9769

In [10]:
param_grid_rf = {
    "n_estimators": [100, 200],
    "max_depth": [6, 10, None],
    "min_samples_leaf": [1, 2, 4],
    "class_weight": ["balanced", "balanced_subsample"],
}
grid_rf = GridSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=-1),
    param_grid_rf,
    scoring=SCORING_AP,
    cv=cv,
    n_jobs=-1,
    refit=True,
)
grid_rf.fit(X_train, y_train)
best_rf = grid_rf.best_estimator_
print("RF best params:", grid_rf.best_params_)
print("RF best CV average_precision:", round(grid_rf.best_score_, 4))

RF best params: {'class_weight': 'balanced', 'max_depth': None, 'min_samples_leaf': 1, 'n_estimators': 100}
RF best CV average_precision: 1.0

## 6. Gradient boosting: grid + early stopping (val = `X_es`)

We maximize **average precision on `X_es`** after training on `X_fit` with early stopping.

In [11]:
def eval_ap(model, X, y):
    p = model.predict_proba(X)[:, 1]
    return average_precision_score(y, p)


def grid_search_catboost_early_stop(X_fit, y_fit, X_es, y_es):
    param_grid = {
        "depth": [4, 6, 8],
        "learning_rate": [0.03, 0.05, 0.1],
        "l2_leaf_reg": [1, 3, 5],
    }
    best = None
    best_ap = -1.0
    best_iters = 200
    for depth in param_grid["depth"]:
        for lr in param_grid["learning_rate"]:
            for l2 in param_grid["l2_leaf_reg"]:
                est = CatBoostClassifierWrapper(
                    task_type=CATBOOST_TASK_TYPE,
                    depth=depth,
                    learning_rate=lr,
                    l2_leaf_reg=l2,
                    iterations=2000,
                    random_seed=42,
                    verbose=False,
                    auto_class_weights="Balanced",
                )
                est.fit(
                    X_fit,
                    y_fit,
                    eval_set=(X_es, y_es),
                    early_stopping_rounds=60,
                    verbose=False,
                )
                ap = eval_ap(est, X_es, y_es)
                bi = est.catboost_.get_best_iteration()
                if bi is None:
                    bi = 1999
                if ap > best_ap:
                    best_ap = ap
                    best = est
                    best_iters = int(bi) + 1
                    best_params = {"depth": depth, "learning_rate": lr, "l2_leaf_reg": l2}
    print("CatBoost best (on early-stop val):", best_params, "best_iteration~", best_iters, "AP", round(best_ap, 4))
    return best_params, best_iters


cat_params, cat_iters = grid_search_catboost_early_stop(X_fit, y_fit, X_es, y_es)
X_merge = np.vstack([X_fit, X_es])
y_merge = np.concatenate([y_fit, y_es])
best_cat = CatBoostClassifierWrapper(
    task_type=CATBOOST_TASK_TYPE,
    depth=cat_params["depth"],
    learning_rate=cat_params["learning_rate"],
    l2_leaf_reg=cat_params["l2_leaf_reg"],
    iterations=max(cat_iters, 50),
    random_seed=42,
    verbose=False,
    auto_class_weights="Balanced",
)
best_cat.fit(X_merge, y_merge)

CatBoost best (on early-stop val): {'depth': 8, 'learning_rate': 0.03, 'l2_leaf_reg': 1} best_iteration~ 1995 AP 1.0

CatBoostClassifierWrapper(auto_class_weights='Balanced', depth=8,
                          iterations=1995, l2_leaf_reg=1, learning_rate=0.03,
                          random_seed=42, task_type='GPU', verbose=False)

In [12]:
def grid_search_xgb_early_stop(X_fit, y_fit, X_es, y_es, spw):
    grid = {
        "max_depth": [4, 6, 8],
        "learning_rate": [0.03, 0.05, 0.1],
        "min_child_weight": [1, 3],
        "subsample": [0.8, 1.0],
    }
    best_ap = -1.0
    best_model = None
    best_bi = 100
    best_params = {}
    for md in grid["max_depth"]:
        for lr in grid["learning_rate"]:
            for mcw in grid["min_child_weight"]:
                for subs in grid["subsample"]:
                    m = XGBClassifier(
                        tree_method="hist",
                        device=XGBOOST_DEVICE,
                        max_depth=md,
                        learning_rate=lr,
                        min_child_weight=mcw,
                        subsample=subs,
                        n_estimators=2000,
                        random_state=42,
                        scale_pos_weight=spw,
                        eval_metric="aucpr",
                        verbosity=0,
                        early_stopping_rounds=80,
                    )
                    m.fit(
                        X_fit,
                        y_fit,
                        eval_set=[(X_es, y_es)],
                        verbose=False,
                    )
                    bi = m.best_iteration
                    if bi is None:
                        bi = 0
                    ap = eval_ap(m, X_es, y_es)
                    if ap > best_ap:
                        best_ap = ap
                        best_model = m
                        best_bi = int(bi)
                        best_params = {
                            "max_depth": md,
                            "learning_rate": lr,
                            "min_child_weight": mcw,
                            "subsample": subs,
                        }
    print("XGB best (on early-stop val):", best_params, "best_iteration", best_bi, "AP", round(best_ap, 4))
    return best_params, best_bi


xgb_params, xgb_bi = grid_search_xgb_early_stop(
    X_fit, y_fit, X_es, y_es, scale_pos_weight
)
best_xgb = XGBClassifier(
    tree_method="hist",
    device=XGBOOST_DEVICE,
    max_depth=xgb_params["max_depth"],
    learning_rate=xgb_params["learning_rate"],
    min_child_weight=xgb_params["min_child_weight"],
    subsample=xgb_params["subsample"],
    n_estimators=max(xgb_bi + 1, 50),
    random_state=42,
    scale_pos_weight=scale_pos_weight,
    eval_metric="aucpr",
    verbosity=0,
)
best_xgb.fit(X_merge, y_merge)

XGB best (on early-stop val): {'max_depth': 6, 'learning_rate': 0.1, 'min_child_weight': 1, 'subsample': 1.0} best_iteration 108 AP 1.0

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cuda', early_stopping_rounds=None,
              enable_categorical=False, eval_metric='aucpr', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=1, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=109,
              n_jobs=None, num_parallel_tree=None, ...)

In [13]:
import lightgbm as lgb


def grid_search_lgb_early_stop(X_fit, y_fit, X_es, y_es):
    grid = {
        "max_depth": [4, 6, 8],
        "learning_rate": [0.03, 0.05, 0.1],
        "min_child_samples": [5, 20, 40],
        "num_leaves": [31, 63],
    }
    best_ap = -1.0
    best_bi = 100
    best_params = {}
    for md in grid["max_depth"]:
        for lr in grid["learning_rate"]:
            for mcs in grid["min_child_samples"]:
                for nl in grid["num_leaves"]:
                    m = LGBMClassifier(
                        device=LIGHTGBM_DEVICE,
                        max_depth=md,
                        learning_rate=lr,
                        min_child_samples=mcs,
                        num_leaves=nl,
                        n_estimators=2000,
                        random_state=42,
                        class_weight="balanced",
                        verbosity=-1,
                    )
                    m.fit(
                        X_fit,
                        y_fit,
                        eval_set=[(X_es, y_es)],
                        eval_metric="auc",
                        callbacks=[
                            lgb.log_evaluation(period=0),
                            lgb.early_stopping(
                                stopping_rounds=60,
                                first_metric_only=True,
                                verbose=False,
                            ),
                        ],
                    )
                    bi = m.best_iteration_
                    if bi is None:
                        bi = 0
                    ap = eval_ap(m, X_es, y_es)
                    if ap > best_ap:
                        best_ap = ap
                        best_bi = int(bi)
                        best_params = {
                            "max_depth": md,
                            "learning_rate": lr,
                            "min_child_samples": mcs,
                            "num_leaves": nl,
                        }
    print(
        "LGB best (on early-stop val):",
        best_params,
        "best_iteration",
        best_bi,
        "AP",
        round(best_ap, 4),
    )
    return best_params, best_bi


lgb_params, lgb_bi = grid_search_lgb_early_stop(X_fit, y_fit, X_es, y_es)
best_lgb = LGBMClassifier(
    device=LIGHTGBM_DEVICE,
    max_depth=lgb_params["max_depth"],
    learning_rate=lgb_params["learning_rate"],
    min_child_samples=lgb_params["min_child_samples"],
    num_leaves=lgb_params["num_leaves"],
    n_estimators=max(lgb_bi + 1, 50),
    random_state=42,
    class_weight="balanced",
    verbosity=-1,
)
best_lgb.fit(X_merge, y_merge)

1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.

LGB best (on early-stop val): {'max_depth': 4, 'learning_rate': 0.05, 'min_child_samples': 5, 'num_leaves': 31} best_iteration 219 AP 1.0

LGBMClassifier(class_weight='balanced', device='gpu', learning_rate=0.05,
               max_depth=4, min_child_samples=5, n_estimators=220,
               random_state=42, verbosity=-1)

## 7. Refit RF on merged fit+ES (align with boosters)

Grid RF was trained on full `X_train`; for the ensemble we use the same **merge** as boosters so calibration sees consistent behavior. Optional: refit RF on `X_merge` with best params.

In [14]:
best_rf_merge = clone(best_rf)
best_rf_merge.fit(X_merge, y_merge)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

## 8. Sigmoid calibration on `X_cal` (prefit)

In [15]:
def calibrate_prefit(base_fitted, X_cal, y_cal, method="sigmoid"):
    """Post-hoc calibration for an already-fitted classifier.

    sklearn 1.8 removed ``cv='prefit'``. Wrap the base model in
    :class:`~sklearn.frozen.FrozenEstimator` so it is not re-trained;
    internal CV only obtains out-of-fold scores for the calibrator.
    """
    n_pos = int((y_cal == 1).sum())
    n_neg = int((y_cal == 0).sum())
    k = min(5, n_pos, n_neg)
    if k < 2:
        raise ValueError(
            f"Calibration needs >=2 samples per class in X_cal; got pos={n_pos}, neg={n_neg}"
        )
    Xc = np.asarray(X_cal)
    if not hasattr(base_fitted, "classes_"):
        base_fitted.classes_ = np.unique(y_cal)
    if not hasattr(base_fitted, "n_features_in_"):
        base_fitted.n_features_in_ = Xc.shape[1]
    cal = CalibratedClassifierCV(
        estimator=FrozenEstimator(base_fitted),
        method=method,
        cv=k,
    )
    cal.fit(X_cal, y_cal)
    return cal


cal_cat = calibrate_prefit(best_cat, X_cal, y_cal, method="sigmoid")
cal_xgb = calibrate_prefit(best_xgb, X_cal, y_cal, method="sigmoid")
cal_rf = calibrate_prefit(best_rf_merge, X_cal, y_cal, method="sigmoid")
print("Calibrated CatBoost, XGB, RF on calibration slice.")

Calibrated CatBoost, XGB, RF on calibration slice.

## 8b. TabPFN (optional) for four-way blends in section 9

- **Default:** `RUN_TABPFN_BLEND = False` so a long TabPFN fit never starts unexpectedly (and does not compete with another TabPFN notebook/kernel).
- **Enable:** set `RUN_TABPFN_BLEND = True`, ensure **`TABPFN_TOKEN`** is exported (same as `tabpfn.ipynb`), then run this cell before section 9.
- TabPFN is **fit on `X_merge`** (same as boosters / RF merge), then **sigmoid-calibrated** on `X_cal` like the other ensemble members. Section 9 then adds four-way grids, **mean OOF PR** on the 4-simplex, TabPFN tails (15% / 25%), thirds / 50–50 diagnostics, and extra rows in `ensemble_blend_comparison.csv` (with **precision, recall, f1_score, accuracy** on test).

In [16]:
!pip install tabpfn

Collecting tabpfn
  Downloading tabpfn-7.1.1-py3-none-any.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: torch>=2.5 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.21.6 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.0.2)
Requirement already satisfied: scikit-learn>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (1.6.1)
Requirement already satisfied: typing_extensions>=4.12.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (4.15.0)
Requirement already satisfied: scipy>=1.11.1 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (1.16.3)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.3.3)
Requirement already satisfied: einops>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (1.4.1)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.12.3)
Requirement already satisfied: pydantic-settings>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (2.13.1)
Collecting eval-type-backport>=0.2.2 (from tabpfn)
  Downloading eval_type_backport-0.3.1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (1.5.3)
Collecting tabpfn-common-utils>=0.2.13 (from tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn)
  Downloading tabpfn_common_utils-0.2.19-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: filelock>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tabpfn) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (1.3.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (6.0.3)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (4.67.3)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->tabpfn) (0.24.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->tabpfn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->tabpfn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.0->tabpfn) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->tabpfn) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->tabpfn) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->tabpfn) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.10.1->tabpfn) (1.2.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.0->tabpfn) (3.6.0)
Requirement already satisfied: nvidia-ml-py>=13.590.48 in /usr/local/lib/python3.12/dist-packages (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (13.590.48)
Requirement already satisfied: platformdirs>=4 in /usr/local/lib/python3.12/dist-packages (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (4.9.2)
Collecting posthog>=6.7 (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn)
  Downloading posthog-7.12.0-py3-none-any.whl.metadata (6.5 kB)
Collecting requests>=2.32.5 (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn)
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: ruff>=0.11.6 in /usr/local/lib/python3.12/dist-packages (from tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (0.15.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.5->tabpfn) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.5->tabpfn) (1.3.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.19.0->tabpfn) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from posthog>=6.7->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (1.17.0)
Collecting backoff>=1.10.0 (from posthog>=6.7->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from posthog>=6.7->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.5->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.5->tabpfn-common-utils>=0.2.13->tabpfn-common-utils[telemetry-interactive]>=0.2.13->tabpfn) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.5->tabpfn) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.5->tabpfn) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->huggingface-hub>=0.19.0->tabpfn) (0.24.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.19.0->tabpfn) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.19.0->tabpfn) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->huggingface-hub>=0.19.0->tabpfn) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.19.0->tabpfn) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.19.0->tabpfn) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->huggingface-hub>=0.19.0->tabpfn) (0.1.2)
Downloading tabpfn-7.1.1-py3-none-any.whl (660 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 660.6/660.6 kB 14.7 MB/s eta 0:00:00
Downloading eval_type_backport-0.3.1-py3-none-any.whl (6.1 kB)
Downloading tabpfn_common_utils-0.2.19-py3-none-any.whl (37 kB)
Downloading posthog-7.12.0-py3-none-any.whl (226 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.9/226.9 kB 17.2 MB/s eta 0:00:00
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 4.6 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Installing collected packages: requests, eval-type-backport, backoff, posthog, tabpfn-common-utils, tabpfn
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.35.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.25.1 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.33.1 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.2.0 which is incompatible.
Successfully installed backoff-2.2.1 eval-type-backport-0.3.1 posthog-7.12.0 requests-2.33.1 tabpfn-7.1.1 tabpfn-common-utils-0.2.19

In [17]:
# Optional TabPFN for §9 four-way blends (off by default).
RUN_TABPFN_BLEND = True
TABPFN_BALANCE_PROBABILITIES = True
TABPFN_N_ESTIMATORS = 8
TABPFN_IGNORE_PRETRAINING_LIMITS = True
try:
    import torch

    TABPFN_DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
except Exception:
    TABPFN_DEVICE = "auto"

TABPFN_BLEND_AVAILABLE = False
cal_tabpfn = None
p_tabpfn_cal = None
p_tabpfn_test = None

# Kaggle: add a Secret named TABPFN_TOKEN (Add-ons → Secrets) so the token is in the env.
if not os.environ.get("TABPFN_TOKEN"):
    try:
        from kaggle_secrets import UserSecretsClient

        os.environ["TABPFN_TOKEN"] = UserSecretsClient().get_secret("TABPFN_TOKEN")
    except Exception:
        pass

if RUN_TABPFN_BLEND:
    if not os.environ.get("TABPFN_TOKEN"):
        print(
            "RUN_TABPFN_BLEND is True but TABPFN_TOKEN is not set; skipping TabPFN. "
            "Set it via section 1b getpass, export in the shell, or Kaggle Secret TABPFN_TOKEN."
        )
    else:
        try:
            from tabpfn import TabPFNClassifier

            _tabpfn_base = TabPFNClassifier(
                random_state=42,
                n_estimators=TABPFN_N_ESTIMATORS,
                device=TABPFN_DEVICE,
                ignore_pretraining_limits=TABPFN_IGNORE_PRETRAINING_LIMITS,
                balance_probabilities=TABPFN_BALANCE_PROBABILITIES,
            )
            _tabpfn_base.fit(X_merge, y_merge)
            cal_tabpfn = calibrate_prefit(_tabpfn_base, X_cal, y_cal, method="sigmoid")
            p_tabpfn_cal = cal_tabpfn.predict_proba(X_cal)[:, 1]
            p_tabpfn_test = cal_tabpfn.predict_proba(X_test)[:, 1]
            TABPFN_BLEND_AVAILABLE = True
            print(
                "TabPFN fit + sigmoid cal OK | PR-AUC cal",
                round(average_precision_score(y_cal, p_tabpfn_cal), 4),
                "| test",
                round(average_precision_score(y_test, p_tabpfn_test), 4),
            )
            # --- TabPFN-only metrics (no ensemble blend); aligns with §10 idea: F1-max threshold on cal ---
            _tgrid_tabpfn = np.arange(0.05, 0.96, 0.01)
            _t_f1max_cal, _best_f1_on_cal = 0.5, -1.0
            for _tv in _tgrid_tabpfn:
                _yh = (p_tabpfn_cal >= _tv).astype(int)
                _fv = f1_score(y_cal, _yh, zero_division=0)
                if _fv > _best_f1_on_cal:
                    _best_f1_on_cal, _t_f1max_cal = _fv, float(_tv)

            def _tabpfn_row_at_t(y_arr, p_arr, t_val):
                y_hat = (p_arr >= t_val).astype(int)
                return {
                    "precision": precision_score(y_arr, y_hat, zero_division=0),
                    "recall": recall_score(y_arr, y_hat, zero_division=0),
                    "f1": f1_score(y_arr, y_hat, zero_division=0),
                    "accuracy": accuracy_score(y_arr, y_hat),
                }

            print("\n=== TabPFN only (sigmoid-calibrated), not blended ===")
            print(
                "Threshold-free | cal PR-AUC",
                round(average_precision_score(y_cal, p_tabpfn_cal), 4),
                "| test PR-AUC",
                round(average_precision_score(y_test, p_tabpfn_test), 4),
                "| cal ROC-AUC",
                round(roc_auc_score(y_cal, p_tabpfn_cal), 4),
                "| test ROC-AUC",
                round(roc_auc_score(y_test, p_tabpfn_test), 4),
            )
            for _lab, _y_arr, _p_arr in (
                ("cal", y_cal, p_tabpfn_cal),
                ("test", y_test, p_tabpfn_test),
            ):
                _m05 = _tabpfn_row_at_t(_y_arr, _p_arr, 0.5)
                _mt = _tabpfn_row_at_t(_y_arr, _p_arr, _t_f1max_cal)
                print(
                    f"@{_lab} t=0.50   | prec {_m05['precision']:.4f} | rec {_m05['recall']:.4f} | f1 {_m05['f1']:.4f} | acc {_m05['accuracy']:.4f}"
                )
                print(
                    f"@{_lab} t={_t_f1max_cal:.3f} (F1-max on cal) | prec {_mt['precision']:.4f} | rec {_mt['recall']:.4f} | f1 {_mt['f1']:.4f} | acc {_mt['accuracy']:.4f}"
                )
            print(
                "(F1-max threshold chosen on cal only; same t applied to cal and test rows above.)\n"
            )
        except Exception as _tabpfn_err:
            TABPFN_BLEND_AVAILABLE = False
            print("TabPFN failed; TABPFN_BLEND_AVAILABLE stays False. Error:", repr(_tabpfn_err))
else:
    print("TabPFN blends: OFF (set RUN_TABPFN_BLEND = True after §8 to add four-way mixes in §9).")

tabpfn-v2.6-classifier-v2.6_default.ckpt:   0%|          | 0.00/43.0M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

TabPFN fit + sigmoid cal OK | PR-AUC cal 1.0 | test 0.7425

=== TabPFN only (sigmoid-calibrated), not blended ===
Threshold-free | cal PR-AUC 1.0 | test PR-AUC 0.7425 | cal ROC-AUC 1.0 | test ROC-AUC 0.9901
@cal t=0.50   | prec 1.0000 | rec 1.0000 | f1 1.0000 | acc 1.0000
@cal t=0.050 (F1-max on cal) | prec 1.0000 | rec 1.0000 | f1 1.0000 | acc 1.0000
@test t=0.50   | prec 1.0000 | rec 0.0556 | f1 0.1053 | acc 0.9836
@test t=0.050 (F1-max on cal) | prec 0.8000 | rec 0.2222 | f1 0.3478 | acc 0.9855
(F1-max threshold chosen on cal only; same t applied to cal and test rows above.)

## 9. Ensemble blends: grids, constraints, CV on cal, diversity penalty, stacking

The blend **table** shows **PR-AUC / ROC-AUC** (threshold-free), then **precision, recall, f1_score, accuracy**, and **`threshold_f1max_cal`** on the **test** set (per-row threshold = **F1-max on the calibration** slice). When **section 8b** is enabled, extra **TabPFN-inclusive** rows appear: four-way grids, **mean OOF PR** on the 4-simplex, no-Cat face, diversity, **15% / 25% TabPFN tails** on 3-way PR/F2 winners, pairwise and one-third diagnostic mixes, and **stacking** on four probabilities.

**GPU / CUDA:** Blends here are **NumPy** (`P @ w`) and **scikit-learn** (metrics, `LogisticRegression` stacking) on **CPU** — the matrices are small, so CUDA would not help. **TabPFN** uses the GPU only when you fit it in **section 8b** (`TABPFN_DEVICE="cuda"` after Colab **Runtime → GPU**). Section **9** just combines probabilities that section 8b already produced on the GPU.

In [18]:
# --- CUDA / device sanity (TabPFN uses GPU in section 8b only; blends below are NumPy/CPU) ---
try:
    import torch

    _cuda_ok = bool(torch.cuda.is_available())
    print("PyTorch CUDA available:", _cuda_ok, end="")
    if _cuda_ok:
        print(" |", torch.cuda.get_device_name(0))
    else:
        print(" (enable Colab Runtime → GPU for TabPFN in section 8b)")
except Exception as _e:
    print("PyTorch check skipped:", _e)

def stack_proba(models, X):
    return np.column_stack([m.predict_proba(X)[:, 1] for m in models])


def blend(P, w):
    w = np.asarray(w, dtype=float)
    w = w / w.sum()
    return (P @ w).ravel()


def simplex_grid_3(step=0.05):
    rows = []
    s = np.arange(0, 1 + step * 0.5, step)
    for a in s:
        for b in s:
            c = 1.0 - a - b
            if c >= -1e-9:
                rows.append([a, b, max(c, 0.0)])
    return np.array(rows)


def max_f2_over_thresholds(y_true, p, t_grid):
    best = 0.0
    for t in t_grid:
        y_hat = (p >= t).astype(int)
        best = max(best, fbeta_score(y_true, y_hat, beta=2, zero_division=0))
    return best


# --- tuning knobs (calibration only; adjust and re-run from §9) ---
TABPFN_BLEND_AVAILABLE = bool(globals().get("TABPFN_BLEND_AVAILABLE", False))
BLEND_MIN_WEIGHT = 0.10  # constrained convex blend: each base model at least this share
BLEND_DIVERSITY_LAMBDA = 0.08  # maximize PR-AUC_cal - lambda * max(w) on the simplex grid
BLEND_CV_FOLDS = 5  # stratified folds on X_cal for mean out-of-fold PR-AUC
# Deploy: pick the candidate below with highest PR-AUC on full X_cal (no test).
# Options: "max_pr_cal_pool" | "nocat_f2_cal" | "stacking_lr_cal"
ENSEMBLE_DEPLOY = "max_pr_cal_pool"

ens_models = [cal_cat, cal_xgb, cal_rf]
P_cal = stack_proba(ens_models, X_cal)
P_test = stack_proba(ens_models, X_test)

t_grid_blend = np.arange(0.05, 0.96, 0.01)


def best_threshold_f1_on_cal(y_cal_arr, p_cal_arr, grid):
    best_t, best_f1 = 0.5, -1.0
    for t in grid:
        y_hat = (p_cal_arr >= t).astype(int)
        fv = f1_score(y_cal_arr, y_hat, zero_division=0)
        if fv > best_f1:
            best_f1, best_t = fv, float(t)
    return best_t


def test_metrics_at_threshold(y_te, p_te, t):
    y_hat = (p_te >= t).astype(int)
    return {
        "precision": precision_score(y_te, y_hat, zero_division=0),
        "recall": recall_score(y_te, y_hat, zero_division=0),
        "f1_score": f1_score(y_te, y_hat, zero_division=0),
        "accuracy": accuracy_score(y_te, y_hat),
        "threshold_f1max_cal": float(t),
    }


W3 = simplex_grid_3(0.05)
W3_constrained = W3[np.all(W3 >= BLEND_MIN_WEIGHT - 1e-9, axis=1)]
if len(W3_constrained) == 0:
    W3_constrained = W3

w_equal = np.array([1 / 3, 1 / 3, 1 / 3])
best_ap, w_ap = -1.0, w_equal.copy()
best_f2c, w_f2 = -1.0, w_equal.copy()
for w in W3:
    p = blend(P_cal, w)
    ap = average_precision_score(y_cal, p)
    if ap > best_ap:
        best_ap, w_ap = ap, w.copy()
    f2c = max_f2_over_thresholds(y_cal, p, t_grid_blend)
    if f2c > best_f2c:
        best_f2c, w_f2 = f2c, w.copy()

best_ap_c, w_ap_constrained = -1.0, w_equal.copy()
for w in W3_constrained:
    ap = average_precision_score(y_cal, blend(P_cal, w))
    if ap > best_ap_c:
        best_ap_c, w_ap_constrained = ap, w.copy()

best_div, w_div = -1e18, w_equal.copy()
for w in W3:
    p = blend(P_cal, w)
    ap = average_precision_score(y_cal, p)
    sc = ap - BLEND_DIVERSITY_LAMBDA * float(np.max(w))
    if sc > best_div:
        best_div, w_div = sc, w.copy()

cv_fold_Py = []
skf_blend = StratifiedKFold(n_splits=BLEND_CV_FOLDS, shuffle=True, random_state=42)
for _, val_idx in skf_blend.split(X_cal, y_cal):
    P_v = stack_proba(ens_models, X_cal[val_idx])
    y_v = y_cal[val_idx]
    cv_fold_Py.append((P_v, y_v))


def mean_oof_pr_auc(w):
    return float(
        np.mean(
            [average_precision_score(yv, blend(Pv, w)) for Pv, yv in cv_fold_Py]
        )
    )


best_cv, w_cv = -1.0, w_equal.copy()
for w in W3:
    m = mean_oof_pr_auc(w)
    if m > best_cv:
        best_cv, w_cv = m, w.copy()

best_ap_2, w_xgb_rf = -1.0, np.array([0.5, 0.5])
best_f2_2, w_xgb_rf_f2 = -1.0, np.array([0.5, 0.5])
for wx in np.arange(0, 1.0001, 0.05):
    wr = 1.0 - wx
    w = np.array([0.0, wx, wr])
    p = blend(P_cal, w)
    ap = average_precision_score(y_cal, p)
    if ap > best_ap_2:
        best_ap_2, w_xgb_rf = ap, np.array([wx, wr])
    f2c = max_f2_over_thresholds(y_cal, p, t_grid_blend)
    if f2c > best_f2_2:
        best_f2_2, w_xgb_rf_f2 = f2c, np.array([wx, wr])

w_nocat_ap = np.array([0.0, w_xgb_rf[0], w_xgb_rf[1]])
w_nocat_f2 = np.array([0.0, w_xgb_rf_f2[0], w_xgb_rf_f2[1]])

stack_lr = LogisticRegression(
    max_iter=2000, class_weight="balanced", random_state=42, solver="lbfgs"
)
stack_lr.fit(P_cal, y_cal)
p_cal_stack = stack_lr.predict_proba(P_cal)[:, 1]
p_test_stack = stack_lr.predict_proba(P_test)[:, 1]


def simplex_grid_4(step=0.1):
    rows = []
    s = np.arange(0, 1 + step * 0.5, step)
    for a in s:
        for b in s:
            for c in s:
                d = 1.0 - a - b - c
                if d >= -1e-9:
                    rows.append([a, b, c, max(d, 0.0)])
    return np.array(rows)


def row_variant_4(name, w):
    w = np.asarray(w, dtype=float)
    p_c = blend(P_cal_4, w)
    p_te = blend(P_test_4, w)
    t_opt = best_threshold_f1_on_cal(y_cal, p_c, t_grid_blend)
    row = {
        "variant": name,
        "w_cat": w[0],
        "w_xgb": w[1],
        "w_rf": w[2],
        "w_tabpfn": w[3],
        "pr_auc_cal": average_precision_score(y_cal, p_c),
        "max_f2_cal": max_f2_over_thresholds(y_cal, p_c, t_grid_blend),
        "pr_auc_test": average_precision_score(y_test, p_te),
        "roc_auc_test": roc_auc_score(y_test, p_te),
    }
    row.update(test_metrics_at_threshold(y_test, p_te, t_opt))
    return row


if TABPFN_BLEND_AVAILABLE:
    P_cal_4 = np.column_stack([P_cal, p_tabpfn_cal])
    P_test_4 = np.column_stack([P_test, p_tabpfn_test])
    W4 = simplex_grid_4(0.1)
    W4_constrained = W4[np.all(W4 >= BLEND_MIN_WEIGHT - 1e-9, axis=1)]
    if len(W4_constrained) == 0:
        W4_constrained = W4
    w4_equal = np.array([0.25, 0.25, 0.25, 0.25])
    best_ap4, w_ap4 = -1.0, w4_equal.copy()
    best_f24, w_f24 = -1.0, w4_equal.copy()
    for w in W4:
        p = blend(P_cal_4, w)
        ap = average_precision_score(y_cal, p)
        if ap > best_ap4:
            best_ap4, w_ap4 = ap, w.copy()
        f2c = max_f2_over_thresholds(y_cal, p, t_grid_blend)
        if f2c > best_f24:
            best_f24, w_f24 = f2c, w.copy()
    best_ap4c, w_ap4_constrained = -1.0, w4_equal.copy()
    for w in W4_constrained:
        ap = average_precision_score(y_cal, blend(P_cal_4, w))
        if ap > best_ap4c:
            best_ap4c, w_ap4_constrained = ap, w.copy()
    stack_lr_4 = LogisticRegression(
        max_iter=2000, class_weight="balanced", random_state=43, solver="lbfgs"
    )
    stack_lr_4.fit(P_cal_4, y_cal)
    p_cal_stack4 = stack_lr_4.predict_proba(P_cal_4)[:, 1]
    p_test_stack4 = stack_lr_4.predict_proba(P_test_4)[:, 1]
    best_div4, w_div4 = -1e18, w4_equal.copy()
    for w in W4:
        p = blend(P_cal_4, w)
        ap = average_precision_score(y_cal, p)
        sc = ap - BLEND_DIVERSITY_LAMBDA * float(np.max(w))
        if sc > best_div4:
            best_div4, w_div4 = sc, w.copy()
    W_nocat4 = np.concatenate([np.zeros((len(W3), 1)), W3], axis=1)
    best_nc_ap, w_nocat_ap4 = -1.0, W_nocat4[0].copy()
    best_nc_f2, w_nocat_f24 = -1.0, W_nocat4[0].copy()
    for w in W_nocat4:
        p = blend(P_cal_4, w)
        ap = average_precision_score(y_cal, p)
        if ap > best_nc_ap:
            best_nc_ap, w_nocat_ap4 = ap, w.copy()
        f2c = max_f2_over_thresholds(y_cal, p, t_grid_blend)
        if f2c > best_nc_f2:
            best_nc_f2, w_nocat_f24 = f2c, w.copy()
    # Same OOF idea as 3-way w_cv: cal-fold splits on X_cal, TabPFN column from fixed cal_tabpfn.
    cv_fold_Py_4 = []
    for _, val_idx in skf_blend.split(X_cal, y_cal):
        P_v3 = stack_proba(ens_models, X_cal[val_idx])
        P_v4 = np.column_stack(
            [P_v3, cal_tabpfn.predict_proba(X_cal[val_idx])[:, 1]]
        )
        cv_fold_Py_4.append((P_v4, y_cal[val_idx]))

    def mean_oof_pr_auc4(w):
        return float(
            np.mean(
                [
                    average_precision_score(yv, blend(Pv, w))
                    for Pv, yv in cv_fold_Py_4
                ]
            )
        )

    best_cv4, w_cv4 = -1.0, w4_equal.copy()
    for w in W4:
        m4 = mean_oof_pr_auc4(w)
        if m4 > best_cv4:
            best_cv4, w_cv4 = m4, w.copy()
else:
    P_cal_4 = P_test_4 = None
    w_ap4 = w_f24 = w_ap4_constrained = w4_equal = None
    w_div4 = w_nocat_ap4 = w_nocat_f24 = None
    w_cv4 = None
    p_cal_stack4 = p_test_stack4 = None


def row_variant(name, w):
    p_c = blend(P_cal, w)
    p_te = blend(P_test, w)
    t_opt = best_threshold_f1_on_cal(y_cal, p_c, t_grid_blend)
    row = {
        "variant": name,
        "w_cat": w[0],
        "w_xgb": w[1],
        "w_rf": w[2],
        "w_tabpfn": float("nan"),
        "pr_auc_cal": average_precision_score(y_cal, p_c),
        "max_f2_cal": max_f2_over_thresholds(y_cal, p_c, t_grid_blend),
        "pr_auc_test": average_precision_score(y_test, p_te),
        "roc_auc_test": roc_auc_score(y_test, p_te),
    }
    row.update(test_metrics_at_threshold(y_test, p_te, t_opt))
    return row


def row_from_probs(name, p_c, p_te):
    t_opt = best_threshold_f1_on_cal(y_cal, p_c, t_grid_blend)
    row = {
        "variant": name,
        "w_cat": float("nan"),
        "w_xgb": float("nan"),
        "w_rf": float("nan"),
        "w_tabpfn": float("nan"),
        "pr_auc_cal": average_precision_score(y_cal, p_c),
        "max_f2_cal": max_f2_over_thresholds(y_cal, p_c, t_grid_blend),
        "pr_auc_test": average_precision_score(y_test, p_te),
        "roc_auc_test": roc_auc_score(y_test, p_te),
    }
    row.update(test_metrics_at_threshold(y_test, p_te, t_opt))
    return row


blend_rows = [
    row_variant("equal_1/3", w_equal),
    row_variant("grid_max_pr_auc_cal", w_ap),
    row_variant(
        f"grid_max_pr_auc_cal_min_w{int(round(BLEND_MIN_WEIGHT * 100))}pct",
        w_ap_constrained,
    ),
    row_variant(
        f"grid_pr_minus_{BLEND_DIVERSITY_LAMBDA:g}x_maxw",
        w_div,
    ),
    row_variant(f"grid_mean_{BLEND_CV_FOLDS}fold_oof_pr_cal", w_cv),
    row_variant("grid_max_f2_cal", w_f2),
    row_variant("nocat_max_pr_auc_cal", w_nocat_ap),
    row_variant("nocat_max_f2_cal", w_nocat_f2),
    row_from_probs("stacking_lr_on_probs_cal", p_cal_stack, p_test_stack),
]
if TABPFN_BLEND_AVAILABLE:
    blend_rows += [
        row_variant_4("four_equal_1/4", w4_equal),
        row_variant_4("four_grid_max_pr_auc_cal", w_ap4),
        row_variant_4(
            f"four_grid_mean_{BLEND_CV_FOLDS}fold_oof_pr_cal",
            w_cv4,
        ),
        row_variant_4(
            f"four_grid_max_pr_min_w{int(round(BLEND_MIN_WEIGHT * 100))}pct",
            w_ap4_constrained,
        ),
        row_variant_4("four_grid_max_f2_cal", w_f24),
        row_variant_4("tabpfn_only_calibrated", np.array([0.0, 0.0, 0.0, 1.0])),
        row_variant_4(
            "three_way_pr_winner_plus_tabpfn_15pct",
            np.array(
                [
                    0.85 * w_ap[0],
                    0.85 * w_ap[1],
                    0.85 * w_ap[2],
                    0.15,
                ]
            ),
        ),
        row_variant_4(
            "three_way_f2_winner_plus_tabpfn_15pct",
            np.array(
                [
                    0.85 * w_f2[0],
                    0.85 * w_f2[1],
                    0.85 * w_f2[2],
                    0.15,
                ]
            ),
        ),
        row_variant_4(
            f"four_grid_pr_minus_{BLEND_DIVERSITY_LAMBDA:g}x_maxw",
            w_div4,
        ),
        row_variant_4("four_nocat_max_pr_auc_cal", w_nocat_ap4),
        row_variant_4("four_nocat_max_f2_cal", w_nocat_f24),
        row_variant_4("cat_tabpfn_50_50", np.array([0.5, 0.0, 0.0, 0.5])),
        row_variant_4(
            "xgb_rf_tabpfn_equal_thirds",
            np.array([0.0, 1.0 / 3, 1.0 / 3, 1.0 / 3]),
        ),
        row_variant_4(
            "three_way_pr_winner_plus_tabpfn_25pct",
            np.array(
                [
                    0.75 * w_ap[0],
                    0.75 * w_ap[1],
                    0.75 * w_ap[2],
                    0.25,
                ]
            ),
        ),
        row_variant_4(
            "three_way_f2_winner_plus_tabpfn_25pct",
            np.array(
                [
                    0.75 * w_f2[0],
                    0.75 * w_f2[1],
                    0.75 * w_f2[2],
                    0.25,
                ]
            ),
        ),
        row_variant_4(
            "cat_xgb_tabpfn_equal_thirds",
            np.array([1.0 / 3, 1.0 / 3, 0.0, 1.0 / 3]),
        ),
        row_variant_4(
            "cat_rf_tabpfn_equal_thirds",
            np.array([1.0 / 3, 0.0, 1.0 / 3, 1.0 / 3]),
        ),
        row_variant_4(
            "xgb_tabpfn_50_50",
            np.array([0.0, 0.5, 0.0, 0.5]),
        ),
        row_variant_4(
            "rf_tabpfn_50_50",
            np.array([0.0, 0.0, 0.5, 0.5]),
        ),
        row_variant_4(
            "cat_tabpfn_rf_thirds_xgb_tail",
            np.array([0.30, 0.10, 0.30, 0.30]),
        ),
        row_from_probs("four_stacking_lr_on_probs_cal", p_cal_stack4, p_test_stack4),
    ]
blend_table = pd.DataFrame(blend_rows)
for _c_extra in ("w_lgb", "w_lr"):
    if _c_extra not in blend_table.columns:
        blend_table[_c_extra] = np.nan
_blend_display_cols = [
    "variant",
    "w_cat",
    "w_xgb",
    "w_rf",
    "w_tabpfn",
    "w_lgb",
    "w_lr",
    "pr_auc_cal",
    "max_f2_cal",
    "pr_auc_test",
    "roc_auc_test",
    "precision",
    "recall",
    "f1_score",
    "accuracy",
    "threshold_f1max_cal",
]
_blend_view = blend_table[
    [c for c in _blend_display_cols if c in blend_table.columns]
].round(4)
display(_blend_view)
# Kaggle / long-log: plain text so the table is always visible in stdout.
print("\n=== Ensemble blend comparison (full table, text) ===\n")
print(_blend_view.to_string())
blend_table.to_csv(os.path.join(RESULT_DIR, "ensemble_blend_comparison.csv"), index=False)

pool_pr_cal = {
    "equal_1/3": (blend(P_cal, w_equal), blend(P_test, w_equal)),
    "grid_max_pr_auc_cal": (blend(P_cal, w_ap), blend(P_test, w_ap)),
    "nocat_max_pr_auc_cal": (blend(P_cal, w_nocat_ap), blend(P_test, w_nocat_ap)),
    f"grid_max_pr_min_w{int(round(BLEND_MIN_WEIGHT * 100))}pct": (
        blend(P_cal, w_ap_constrained),
        blend(P_test, w_ap_constrained),
    ),
    f"grid_pr_minus_{BLEND_DIVERSITY_LAMBDA:g}x_maxw": (
        blend(P_cal, w_div),
        blend(P_test, w_div),
    ),
    f"mean_{BLEND_CV_FOLDS}fold_oof_pr": (
        blend(P_cal, w_cv),
        blend(P_test, w_cv),
    ),
    "nocat_max_f2_cal": (blend(P_cal, w_nocat_f2), blend(P_test, w_nocat_f2)),
    "stacking_lr_cal": (p_cal_stack, p_test_stack),
}

if ENSEMBLE_DEPLOY == "max_pr_cal_pool":
    win_name = max(
        pool_pr_cal,
        key=lambda k: average_precision_score(y_cal, pool_pr_cal[k][0]),
    )
    p_cal, p_test = pool_pr_cal[win_name]
elif ENSEMBLE_DEPLOY == "nocat_f2_cal":
    win_name = "nocat_max_f2_cal"
    p_cal, p_test = pool_pr_cal[win_name]
elif ENSEMBLE_DEPLOY == "stacking_lr_cal":
    win_name = "stacking_lr_cal"
    p_cal, p_test = pool_pr_cal[win_name]
else:
    raise ValueError(f"Unknown ENSEMBLE_DEPLOY={ENSEMBLE_DEPLOY!r}")

p_test_equal = blend(P_test, w_equal)
p_test_unc_pr = blend(P_test, w_ap)
pr_test_equal = average_precision_score(y_test, p_test_equal)
pr_test_unc = average_precision_score(y_test, p_test_unc_pr)
print(
    "Tradeoff (test — for diagnostics only): unconstrained cal-PR grid winner vs equal blend —",
    "test PR-AUC",
    round(pr_test_unc, 4),
    "vs",
    round(pr_test_equal, 4),
)
print(
    "Downstream sections 10–11 deploy:",
    ENSEMBLE_DEPLOY,
    "→",
    win_name,
    "| cal PR-AUC",
    round(average_precision_score(y_cal, p_cal), 4),
    "| test PR-AUC",
    round(average_precision_score(y_test, p_test), 4),
    "| test ROC",
    round(roc_auc_score(y_test, p_test), 4),
)
if win_name == "stacking_lr_cal":
    print("Stacking LR coef (cat, xgb, rf):", np.round(stack_lr.coef_.ravel(), 4).tolist())

PyTorch CUDA available: True | Tesla T4

,variant,w_cat,w_xgb,w_rf,w_tabpfn,w_lgb,w_lr,pr_auc_cal,max_f2_cal,pr_auc_test,roc_auc_test,precision,recall,f1_score,accuracy,threshold_f1max_cal
0,equal_1/3,0.3333,0.3333,0.3333,NaN,NaN,NaN,0.9998,0.9964,0.5787,0.9630,0.7500,0.3333,0.4615,0.9865,0.40
1,grid_max_pr_auc_cal,0.0000,0.1000,0.9000,NaN,NaN,NaN,0.9998,0.9967,0.4415,0.9595,0.7143,0.2778,0.4000,0.9855,0.25
2,grid_max_pr_auc_cal_min_w10pct,0.1000,0.1000,0.8000,NaN,NaN,NaN,0.9998,0.9964,0.4699,0.9609,1.0000,0.0556,0.1053,0.9836,0.74
3,grid_pr_minus_0.08x_maxw,0.3000,0.3500,0.3500,NaN,NaN,NaN,0.9998,0.9964,0.5723,0.9630,0.7500,0.3333,0.4615,0.9865,0.41
4,grid_mean_5fold_oof_pr_cal,0.0000,0.1000,0.9000,NaN,NaN,NaN,0.9998,0.9967,0.4415,0.9595,0.7143,0.2778,0.4000,0.9855,0.25
5,grid_max_f2_cal,0.0000,0.0500,0.9500,NaN,NaN,NaN,0.9998,0.9967,0.4329,0.9591,0.7143,0.2778,0.4000,0.9855,0.23
6,nocat_max_pr_auc_cal,0.0000,0.1000,0.9000,NaN,NaN,NaN,0.9998,0.9967,0.4415,0.9595,0.7143,0.2778,0.4000,0.9855,0.25
7,nocat_max_f2_cal,0.0000,0.0500,0.9500,NaN,NaN,NaN,0.9998,0.9967,0.4329,0.9591,0.7143,0.2778,0.4000,0.9855,0.23
8,stacking_lr_on_probs_cal,NaN,NaN,NaN,NaN,NaN,NaN,0.9998,0.9964,0.5774,0.9629,0.7500,0.3333,0.4615,0.9865,0.32
9,four_equal_1/4,0.2500,0.2500,0.2500,0.2500,NaN,NaN,1.0000,0.9990,0.5977,0.9694,0.7500,0.3333,0.4615,0.9865,0.25
10,four_grid_max_pr_auc_cal,0.0000,0.0000,0.0000,1.0000,NaN,NaN,1.0000,1.0000,0.7425,0.9901,0.8000,0.2222,0.3478,0.9855,0.05
11,four_grid_mean_5fold_oof_pr_cal,0.0000,0.0000,0.0000,1.0000,NaN,NaN,1.0000,1.0000,0.7425,0.9901,0.8000,0.2222,0.3478,0.9855,0.05
12,four_grid_max_pr_min_w10pct,0.1000,0.1000,0.1000,0.7000,NaN,NaN,1.0000,1.0000,0.6445,0.9784,0.7500,0.1667,0.2727,0.9846,0.25
13,four_grid_max_f2_cal,0.0000,0.0000,0.0000,1.0000,NaN,NaN,1.0000,1.0000,0.7425,0.9901,0.8000,0.2222,0.3478,0.9855,0.05
14,tabpfn_only_calibrated,0.0000,0.0000,0.0000,1.0000,NaN,NaN,1.0000,1.0000,0.7425,0.9901,0.8000,0.2222,0.3478,0.9855,0.05
15,three_way_pr_winner_plus_tabpfn_15pct,0.0000,0.0850,0.7650,0.1500,NaN,NaN,1.0000,0.9990,0.4499,0.9610,0.6000,0.3333,0.4286,0.9846,0.14
16,three_way_f2_winner_plus_tabpfn_15pct,0.0000,0.0425,0.8075,0.1500,NaN,NaN,1.0000,0.9990,0.4408,0.9606,0.6667,0.3333,0.4444,0.9855,0.14
17,four_grid_pr_minus_0.08x_maxw,0.2000,0.2000,0.3000,0.3000,NaN,NaN,1.0000,0.9997,0.5772,0.9681,0.7500,0.3333,0.4615,0.9865,0.28
18,four_nocat_max_pr_auc_cal,0.0000,0.0000,0.0000,1.0000,NaN,NaN,1.0000,1.0000,0.7425,0.9901,0.8000,0.2222,0.3478,0.9855,0.05
19,four_nocat_max_f2_cal,0.0000,0.0000,0.0000,1.0000,NaN,NaN,1.0000,1.0000,0.7425,0.9901,0.8000,0.2222,0.3478,0.9855,0.05
20,cat_tabpfn_50_50,0.5000,0.0000,0.0000,0.5000,NaN,NaN,1.0000,1.0000,0.6589,0.9687,0.8000,0.2222,0.3478,0.9855,0.38
21,xgb_rf_tabpfn_equal_thirds,0.0000,0.3333,0.3333,0.3333,NaN,NaN,1.0000,0.9993,0.5566,0.9682,0.8571,0.3333,0.4800,0.9875,0.32
22,three_way_pr_winner_plus_tabpfn_25pct,0.0000,0.0750,0.6750,0.2500,NaN,NaN,1.0000,0.9993,0.4785,0.9638,0.7500,0.3333,0.4615,0.9865,0.19
23,three_way_f2_winner_plus_tabpfn_25pct,0.0000,0.0375,0.7125,0.2500,NaN,NaN,1.0000,0.9993,0.4526,0.9631,0.7500,0.3333,0.4615,0.9865,0.18
24,cat_xgb_tabpfn_equal_thirds,0.3333,0.3333,0.0000,0.3333,NaN,NaN,1.0000,0.9993,0.6604,0.9703,0.7500,0.3333,0.4615,0.9865,0.33
25,cat_rf_tabpfn_equal_thirds,0.3333,0.0000,0.3333,0.3333,NaN,NaN,1.0000,0.9997,0.5638,0.9670,0.8333,0.2778,0.4167,0.9865,0.28
26,xgb_tabpfn_50_50,0.0000,0.5000,0.0000,0.5000,NaN,NaN,1.0000,0.9997,0.6661,0.9752,1.0000,0.2222,0.3636,0.9865,0.49
27,rf_tabpfn_50_50,0.0000,0.0000,0.5000,0.5000,NaN,NaN,1.0000,1.0000,0.4891,0.9671,1.0000,0.1111,0.2000,0.9846,0.41
28,cat_tabpfn_rf_thirds_xgb_tail,0.3000,0.1000,0.3000,0.3000,NaN,NaN,1.0000,0.9997,0.5763,0.9678,0.7500,0.3333,0.4615,0.9865,0.27
29,four_stacking_lr_on_probs_cal,NaN,NaN,NaN,NaN,NaN,NaN,1.0000,0.9997,0.6024,0.9719,0.7500,0.3333,0.4615,0.9865,0.07

=== Ensemble blend comparison (full table, text) ===

                                  variant   w_cat   w_xgb    w_rf  w_tabpfn  w_lgb  w_lr  pr_auc_cal  max_f2_cal  pr_auc_test  roc_auc_test  precision  recall  f1_score  accuracy  threshold_f1max_cal
0                               equal_1/3  0.3333  0.3333  0.3333       NaN    NaN   NaN      0.9998      0.9964       0.5787        0.9630     0.7500  0.3333    0.4615    0.9865                 0.40
1                     grid_max_pr_auc_cal  0.0000  0.1000  0.9000       NaN    NaN   NaN      0.9998      0.9967       0.4415        0.9595     0.7143  0.2778    0.4000    0.9855                 0.25
2          grid_max_pr_auc_cal_min_w10pct  0.1000  0.1000  0.8000       NaN    NaN   NaN      0.9998      0.9964       0.4699        0.9609     1.0000  0.0556    0.1053    0.9836                 0.74
3                grid_pr_minus_0.08x_maxw  0.3000  0.3500  0.3500       NaN    NaN   NaN      0.9998      0.9964       0.5723        0.9630     0.7500  0.3333    0.4615    0.9865                 0.41
4              grid_mean_5fold_oof_pr_cal  0.0000  0.1000  0.9000       NaN    NaN   NaN      0.9998      0.9967       0.4415        0.9595     0.7143  0.2778    0.4000    0.9855                 0.25
5                         grid_max_f2_cal  0.0000  0.0500  0.9500       NaN    NaN   NaN      0.9998      0.9967       0.4329        0.9591     0.7143  0.2778    0.4000    0.9855                 0.23
6                    nocat_max_pr_auc_cal  0.0000  0.1000  0.9000       NaN    NaN   NaN      0.9998      0.9967       0.4415        0.9595     0.7143  0.2778    0.4000    0.9855                 0.25
7                        nocat_max_f2_cal  0.0000  0.0500  0.9500       NaN    NaN   NaN      0.9998      0.9967       0.4329        0.9591     0.7143  0.2778    0.4000    0.9855                 0.23
8                stacking_lr_on_probs_cal     NaN     NaN     NaN       NaN    NaN   NaN      0.9998      0.9964       0.5774        0.9629     0.7500  0.3333    0.4615    0.9865                 0.32
9                          four_equal_1/4  0.2500  0.2500  0.2500    0.2500    NaN   NaN      1.0000      0.9990       0.5977        0.9694     0.7500  0.3333    0.4615    0.9865                 0.25
10               four_grid_max_pr_auc_cal  0.0000  0.0000  0.0000    1.0000    NaN   NaN      1.0000      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
11        four_grid_mean_5fold_oof_pr_cal  0.0000  0.0000  0.0000    1.0000    NaN   NaN      1.0000      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
12            four_grid_max_pr_min_w10pct  0.1000  0.1000  0.1000    0.7000    NaN   NaN      1.0000      1.0000       0.6445        0.9784     0.7500  0.1667    0.2727    0.9846                 0.25
13                   four_grid_max_f2_cal  0.0000  0.0000  0.0000    1.0000    NaN   NaN      1.0000      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
14                 tabpfn_only_calibrated  0.0000  0.0000  0.0000    1.0000    NaN   NaN      1.0000      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
15  three_way_pr_winner_plus_tabpfn_15pct  0.0000  0.0850  0.7650    0.1500    NaN   NaN      1.0000      0.9990       0.4499        0.9610     0.6000  0.3333    0.4286    0.9846                 0.14
16  three_way_f2_winner_plus_tabpfn_15pct  0.0000  0.0425  0.8075    0.1500    NaN   NaN      1.0000      0.9990       0.4408        0.9606     0.6667  0.3333    0.4444    0.9855                 0.14
17          four_grid_pr_minus_0.08x_maxw  0.2000  0.2000  0.3000    0.3000    NaN   NaN      1.0000      0.9997       0.5772        0.9681     0.7500  0.3333    0.4615    0.9865                 0.28
18              four_nocat_max_pr_auc_cal  0.0000  0.0000  0.0000    1.0000    NaN   NaN      1.0000      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
19                  four_nocat_max_f2_cal  0.0000  0.0000  0.0000    1.0000    NaN   NaN      1.0000      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
20                       cat_tabpfn_50_50  0.5000  0.0000  0.0000    0.5000    NaN   NaN      1.0000      1.0000       0.6589        0.9687     0.8000  0.2222    0.3478    0.9855                 0.38
21             xgb_rf_tabpfn_equal_thirds  0.0000  0.3333  0.3333    0.3333    NaN   NaN      1.0000      0.9993       0.5566        0.9682     0.8571  0.3333    0.4800    0.9875                 0.32
22  three_way_pr_winner_plus_tabpfn_25pct  0.0000  0.0750  0.6750    0.2500    NaN   NaN      1.0000      0.9993       0.4785        0.9638     0.7500  0.3333    0.4615    0.9865                 0.19
23  three_way_f2_winner_plus_tabpfn_25pct  0.0000  0.0375  0.7125    0.2500    NaN   NaN      1.0000      0.9993       0.4526        0.9631     0.7500  0.3333    0.4615    0.9865                 0.18
24            cat_xgb_tabpfn_equal_thirds  0.3333  0.3333  0.0000    0.3333    NaN   NaN      1.0000      0.9993       0.6604        0.9703     0.7500  0.3333    0.4615    0.9865                 0.33
25             cat_rf_tabpfn_equal_thirds  0.3333  0.0000  0.3333    0.3333    NaN   NaN      1.0000      0.9997       0.5638        0.9670     0.8333  0.2778    0.4167    0.9865                 0.28
26                       xgb_tabpfn_50_50  0.0000  0.5000  0.0000    0.5000    NaN   NaN      1.0000      0.9997       0.6661        0.9752     1.0000  0.2222    0.3636    0.9865                 0.49
27                        rf_tabpfn_50_50  0.0000  0.0000  0.5000    0.5000    NaN   NaN      1.0000      1.0000       0.4891        0.9671     1.0000  0.1111    0.2000    0.9846                 0.41
28          cat_tabpfn_rf_thirds_xgb_tail  0.3000  0.1000  0.3000    0.3000    NaN   NaN      1.0000      0.9997       0.5763        0.9678     0.7500  0.3333    0.4615    0.9865                 0.27
29          four_stacking_lr_on_probs_cal     NaN     NaN     NaN       NaN    NaN   NaN      1.0000      0.9997       0.6024        0.9719     0.7500  0.3333    0.4615    0.9865                 0.07
Tradeoff (test — for diagnostics only): unconstrained cal-PR grid winner vs equal blend — test PR-AUC 0.4415 vs 0.5787
Downstream sections 10–11 deploy: max_pr_cal_pool → grid_max_pr_auc_cal | cal PR-AUC 0.9998 | test PR-AUC 0.4415 | test ROC 0.9595

## 9b. Learned convex blend weights (optimize on cal)

**Why the old SLSQP cell often returned 1/3, 1/3, 1/3:** `average_precision` is a **ranking** objective. With **equality `sum(w)=1`**, SciPy’s **SLSQP** uses finite differences; at a **symmetric** start the projected gradient can be ~**0** in one iteration, so the solver **never moves** even when other weights are better.

**What this cell does instead**

1. **Softmax parameterization** `w = softmax(z)` (unconstrained `z`), **L-BFGS-B** on **negative PR-AUC**, with **several random restarts** + **`differential_evolution`** fallback on `z` (still softmax → valid `w`).
2. **Wide stack:** sigmoid-calibrated probs for **Cat, XGB, RF, LGB, LR**, plus **TabPFN** if §8b ran — not only the three columns of `P_cal`.
3. **Optional “neural” baseline:** tiny **PyTorch** `softmax(logits)` trained with **Adam** to minimize **BCE** on cal (not PR-AUC; included because it is smooth and can differ from the PR-AUC optimum).

**Requires:** §8 (calibration helpers), §9 (so `blend`, `y_cal`, models exist). Uses `calibrate_prefit` + `clone` for LGB/LR on the cal slice.

**Note:** §9 **logistic stacking** on base probs is another learned mixer (can use negative weights); this §9b keeps a **proper convex combination** `w ≥ 0`, `∑w = 1`.

In [19]:
from scipy.optimize import differential_evolution, minimize
import json

# --- Softmax on R^n → simplex; avoids degenerate SLSQP at w = 1/n ---


def _softmax(z):
    z = np.asarray(z, dtype=float).ravel()
    z = z - np.max(z)
    e = np.exp(z)
    return e / (np.sum(e) + 1e-15)


def _neg_pr_auc_softmax(z, P, y):
    w = _softmax(z)
    p = np.clip((P @ w).ravel(), 1e-12, 1.0 - 1e-12)
    return -float(average_precision_score(np.asarray(y).astype(int).ravel(), p))


def learn_blend_weights_pr_auc(P, y, n_restarts=8, seed=42):
    """Convex weights maximizing PR-AUC on y; softmax + L-BFGS-B + DE fallback."""
    P = np.asarray(P, dtype=float)
    y = np.asarray(y).astype(int).ravel()
    n = P.shape[1]
    rng = np.random.RandomState(seed)

    best_z, best_val = None, np.inf
    starts = [np.zeros(n)]
    for _ in range(n_restarts - 1):
        starts.append(rng.standard_normal(n))

    for z0 in starts:
        res = minimize(
            _neg_pr_auc_softmax,
            z0,
            args=(P, y),
            method="L-BFGS-B",
            options={"maxiter": 500, "ftol": 1e-10},
        )
        if res.fun < best_val:
            best_val, best_z = res.fun, res.x

    def _obj(z_flat):
        return _neg_pr_auc_softmax(np.asarray(z_flat, dtype=float), P, y)

    de = differential_evolution(
        _obj,
        bounds=[(-4.0, 4.0)] * n,
        seed=seed,
        maxiter=120,
        polish=True,
    )
    if de.fun < best_val:
        best_val, best_z = de.fun, de.x

    w = _softmax(best_z)
    return w, {"lbfgs_best_neg_ap": float(best_val), "de_success": bool(de.success)}


def build_wide_calibrated_probs():
    """Stack sigmoid-calibrated P[:,k] for all main models (same protocol as section 8)."""
    cols_cal = []
    cols_test = []
    names = []

    def add(name, cal_est):
        cols_cal.append(cal_est.predict_proba(X_cal)[:, 1])
        cols_test.append(cal_est.predict_proba(X_test)[:, 1])
        names.append(name)

    add("Cat_cal", cal_cat)
    add("XGB_cal", cal_xgb)
    add("RF_cal", cal_rf)

    if "best_lgb" in globals():
        cal_lgb = calibrate_prefit(best_lgb, X_cal, y_cal, method="sigmoid")
        add("LGB_cal", cal_lgb)
    if "best_lr" in globals():
        cal_lr = calibrate_prefit(best_lr, X_cal, y_cal, method="sigmoid")
        add("LR_cal", cal_lr)
    if globals().get("p_tabpfn_cal") is not None and globals().get("p_tabpfn_test") is not None:
        cols_cal.append(np.asarray(p_tabpfn_cal, dtype=float).ravel())
        cols_test.append(np.asarray(p_tabpfn_test, dtype=float).ravel())
        names.append("TabPFN_cal")

    Pc = np.column_stack(cols_cal)
    Pt = np.column_stack(cols_test)
    return Pc, Pt, names


def _torch_learn_softmax_bce(P_cal, y_cal, epochs=400, lr=0.15, seed=42):
    """Optional: Adam on softmax(logits) minimizing BCE(Pw, y) — smooth; not PR-AUC."""
    import torch

    n = int(np.asarray(P_cal).shape[1])
    torch.manual_seed(seed)
    z = torch.zeros(n, requires_grad=True)
    opt = torch.optim.Adam([z], lr=lr)
    P = torch.tensor(np.asarray(P_cal, dtype=np.float32), device="cpu")
    y = torch.tensor(np.asarray(y_cal, dtype=np.float32), device="cpu")
    for _ in range(epochs):
        opt.zero_grad()
        w = torch.softmax(z, dim=0)
        p = (P @ w).clamp(1e-7, 1.0 - 1e-7)
        loss = torch.nn.functional.binary_cross_entropy(p, y)
        loss.backward()
        opt.step()
    w = torch.softmax(z, dim=0).detach().cpu().numpy()
    return w


def _f1_max_threshold_on_cal(y_cal_arr, p_cal_arr, grid=None):
    if grid is None:
        grid = np.arange(0.05, 0.96, 0.01)
    best_t, best_f1 = 0.5, -1.0
    for t in grid:
        y_hat = (p_cal_arr >= t).astype(int)
        fv = f1_score(y_cal_arr, y_hat, zero_division=0)
        if fv > best_f1:
            best_f1, best_t = fv, float(t)
    return best_t, float(best_f1)


def _cls_at_t(y_arr, p_arr, t):
    y_hat = (np.asarray(p_arr).ravel() >= t).astype(int)
    y_arr = np.asarray(y_arr).astype(int).ravel()
    return {
        "precision": precision_score(y_arr, y_hat, zero_division=0),
        "recall": recall_score(y_arr, y_hat, zero_division=0),
        "f1": f1_score(y_arr, y_hat, zero_division=0),
        "accuracy": accuracy_score(y_arr, y_hat),
    }


def _report_learned_metrics_block(title, y_cal_arr, p_cal_arr, y_te_arr, p_te_arr, weights_dict):
    print(f"\n=== {title} ===")
    print(
        "Threshold-free | PR-AUC cal",
        round(average_precision_score(y_cal_arr, p_cal_arr), 4),
        "| test",
        round(average_precision_score(y_te_arr, p_te_arr), 4),
        "| ROC cal",
        round(roc_auc_score(y_cal_arr, p_cal_arr), 4),
        "| ROC test",
        round(roc_auc_score(y_te_arr, p_te_arr), 4),
    )
    t_f1, _ = _f1_max_threshold_on_cal(y_cal_arr, p_cal_arr)
    for split, yv, pv in ("cal", y_cal_arr, p_cal_arr), ("test", y_te_arr, p_te_arr):
        m05 = _cls_at_t(yv, pv, 0.5)
        mt = _cls_at_t(yv, pv, t_f1)
        print(
            f"@{split} t=0.50  | prec {m05['precision']:.4f} | rec {m05['recall']:.4f} | f1 {m05['f1']:.4f} | acc {m05['accuracy']:.4f}"
        )
        print(
            f"@{split} t={t_f1:.3f} (F1-max on cal) | prec {mt['precision']:.4f} | rec {mt['recall']:.4f} | f1 {mt['f1']:.4f} | acc {mt['accuracy']:.4f}"
        )
    print("(F1-max threshold is searched on cal only; same t on cal and test lines.)")
    if weights_dict is not None:
        print("weights:", weights_dict)


def _learned_metric_row(variant, y_cal_arr, p_cal_arr, y_te_arr, p_te_arr, weights_dict):
    t_f1, _ = _f1_max_threshold_on_cal(y_cal_arr, p_cal_arr)
    row = {
        "variant": variant,
        "pr_auc_cal": round(float(average_precision_score(y_cal_arr, p_cal_arr)), 4),
        "pr_auc_test": round(float(average_precision_score(y_te_arr, p_te_arr)), 4),
        "roc_auc_cal": round(float(roc_auc_score(y_cal_arr, p_cal_arr)), 4),
        "roc_auc_test": round(float(roc_auc_score(y_te_arr, p_te_arr)), 4),
        "threshold_f1max_cal": round(t_f1, 4),
        "weights_json": json.dumps(weights_dict) if isinstance(weights_dict, dict) else str(weights_dict),
    }
    for split, yv, pv, suf in (
        ("cal", y_cal_arr, p_cal_arr, "cal"),
        ("test", y_te_arr, p_te_arr, "test"),
    ):
        m05 = _cls_at_t(yv, pv, 0.5)
        mt = _cls_at_t(yv, pv, t_f1)
        for k, v in m05.items():
            row[f"{k}_{suf}_t0p5"] = round(float(v), 4)
        for k, v in mt.items():
            row[f"{k}_{suf}_t_f1max"] = round(float(v), 4)
    return row


def _blend_extra_row(variant, p_c, p_te, w_cat, w_xgb, w_rf, w_tabpfn, w_lgb=np.nan, w_lr=np.nan):
    """Same metric columns as section 9 blend_table (needs t_grid_blend, best_threshold_f1_on_cal, etc. from section 9)."""
    t_opt = best_threshold_f1_on_cal(y_cal, p_c, t_grid_blend)
    row = {
        "variant": variant,
        "w_cat": w_cat,
        "w_xgb": w_xgb,
        "w_rf": w_rf,
        "w_tabpfn": w_tabpfn,
        "w_lgb": w_lgb,
        "w_lr": w_lr,
        "pr_auc_cal": average_precision_score(y_cal, p_c),
        "max_f2_cal": max_f2_over_thresholds(y_cal, p_c, t_grid_blend),
        "pr_auc_test": average_precision_score(y_test, p_te),
        "roc_auc_test": roc_auc_score(y_test, p_te),
    }
    row.update(test_metrics_at_threshold(y_test, p_te, t_opt))
    return row


def _wide_vec_to_weight_slots(w_vec, names):
    m = {
        "Cat_cal": "w_cat",
        "XGB_cal": "w_xgb",
        "RF_cal": "w_rf",
        "LGB_cal": "w_lgb",
        "LR_cal": "w_lr",
        "TabPFN_cal": "w_tabpfn",
    }
    slots = {k: float("nan") for k in ("w_cat", "w_xgb", "w_rf", "w_tabpfn", "w_lgb", "w_lr")}
    for nm, v in zip(names, np.asarray(w_vec, dtype=float).ravel()):
        key = m.get(nm)
        if key is not None:
            slots[key] = float(v)
    return slots


# Globals for section 12 benchmark (set None if 9b skipped)
p_cal_learned_wide_pr = p_test_learned_wide_pr = None
p_cal_learned_wide_bce = p_test_learned_wide_bce = None
p_cal_learned3_pr = p_test_learned3_pr = None
p_cal_learned4_pr = p_test_learned4_pr = None

blend_table_merged = None

if "blend" not in globals() or "y_cal" not in globals():
    print("Run sections 8–9 first (needs cal_* models, y_cal, blend).")
else:
    P_wide_cal, P_wide_test, wide_names = build_wide_calibrated_probs()
    print("Wide stack columns:", wide_names, "| shape cal", P_wide_cal.shape)

    learned_rows = []

    w_pr, info = learn_blend_weights_pr_auc(P_wide_cal, y_cal)
    p_cal_learned_wide_pr = blend(P_wide_cal, w_pr)
    p_test_learned_wide_pr = blend(P_wide_test, w_pr)
    wd = dict(zip(wide_names, np.round(w_pr, 4).tolist()))
    _report_learned_metrics_block(
        "Learned wide convex (max PR-AUC on cal; softmax + L-BFGS + DE)",
        y_cal,
        p_cal_learned_wide_pr,
        y_test,
        p_test_learned_wide_pr,
        wd,
    )
    learned_rows.append(
        _learned_metric_row(
            "learned_wide_pr_auc_on_cal",
            y_cal,
            p_cal_learned_wide_pr,
            y_test,
            p_test_learned_wide_pr,
            wd,
        )
    )

    LEARNED_WIDE_BLEND_WEIGHTS_PR_AUC = dict(zip(wide_names, w_pr.tolist()))
    LEARNED_WIDE_BLEND_INFO = info

    w_bce = None
    try:
        w_bce = _torch_learn_softmax_bce(P_wide_cal, y_cal)
        p_cal_learned_wide_bce = blend(P_wide_cal, w_bce)
        p_test_learned_wide_bce = blend(P_wide_test, w_bce)
        wd_b = dict(zip(wide_names, np.round(w_bce, 4).tolist()))
        _report_learned_metrics_block(
            "Learned wide (PyTorch Adam, softmax, minimize BCE on cal — not PR-AUC objective)",
            y_cal,
            p_cal_learned_wide_bce,
            y_test,
            p_test_learned_wide_bce,
            wd_b,
        )
        learned_rows.append(
            _learned_metric_row(
                "learned_wide_bce_softmax_on_cal",
                y_cal,
                p_cal_learned_wide_bce,
                y_test,
                p_test_learned_wide_bce,
                wd_b,
            )
        )
    except Exception as _e:
        print("\n(PyTorch softmax/BCE skipped:", repr(_e), ")")
        w_bce = None
        p_cal_learned_wide_bce = p_test_learned_wide_bce = None

    if globals().get("P_cal_4") is not None and globals().get("P_test_4") is not None:
        w4_pr, _info4 = learn_blend_weights_pr_auc(P_cal_4, y_cal, n_restarts=8, seed=44)
        p_cal_learned4_pr = blend(P_cal_4, w4_pr)
        p_test_learned4_pr = blend(P_test_4, w4_pr)
        wd4 = {
            "cat": float(w4_pr[0]),
            "xgb": float(w4_pr[1]),
            "rf": float(w4_pr[2]),
            "tabpfn": float(w4_pr[3]),
        }
        _report_learned_metrics_block(
            "Learned 4-model convex on [Cat, XGB, RF, TabPFN] (PR-AUC on cal)",
            y_cal,
            p_cal_learned4_pr,
            y_test,
            p_test_learned4_pr,
            wd4,
        )
        learned_rows.append(
            _learned_metric_row(
                "learned_fourway_pr_auc_on_cal",
                y_cal,
                p_cal_learned4_pr,
                y_test,
                p_test_learned4_pr,
                wd4,
            )
        )
        LEARNED_FOURWAY_BLEND_WEIGHTS_PR_AUC = wd4
    else:
        LEARNED_FOURWAY_BLEND_WEIGHTS_PR_AUC = None

    if "P_cal" in globals():
        w3, _ = learn_blend_weights_pr_auc(P_cal, y_cal, n_restarts=8, seed=43)
        p_cal_learned3_pr = blend(P_cal, w3)
        p_test_learned3_pr = blend(P_test, w3)
        wd3 = {"cat": float(w3[0]), "xgb": float(w3[1]), "rf": float(w3[2])}
        _report_learned_metrics_block(
            "Learned 3-model blend on section 9 P_cal only (PR-AUC on cal)",
            y_cal,
            p_cal_learned3_pr,
            y_test,
            p_test_learned3_pr,
            wd3,
        )
        learned_rows.append(
            _learned_metric_row(
                "learned_3way_pr_auc_on_cal",
                y_cal,
                p_cal_learned3_pr,
                y_test,
                p_test_learned3_pr,
                wd3,
            )
        )

    LEARNED_BLEND_METRICS_DF = pd.DataFrame(learned_rows)

    _sum_cols = [
        c
        for c in [
            "variant",
            "pr_auc_cal",
            "pr_auc_test",
            "roc_auc_cal",
            "roc_auc_test",
            "threshold_f1max_cal",
            "weights_json",
        ]
        if c in LEARNED_BLEND_METRICS_DF.columns
    ]
    _sum_df = LEARNED_BLEND_METRICS_DF[_sum_cols].copy()
    for _c in _sum_df.columns:
        if _sum_df[_c].dtype != object:
            _sum_df[_c] = _sum_df[_c].astype(float).round(4)

    _full_df = LEARNED_BLEND_METRICS_DF.copy()
    for _c in _full_df.columns:
        if _full_df[_c].dtype != object:
            _full_df[_c] = _full_df[_c].astype(float).round(4)

    try:
        from IPython.display import HTML, display as _ipy_disp_lb

        _css = (
            "<style>"
            ".vlst-lb{font-size:15px;line-height:1.35}"
            ".vlst-lb-x{width:100%;overflow-x:auto;overflow-y:visible;margin:10px 0;padding:8px 4px;"
            "border:1px solid #ccc;background:#fff;box-sizing:border-box}"
            ".vlst-lb table{border-collapse:collapse;font-size:15px;white-space:nowrap}"
            ".vlst-lb th,.vlst-lb td{border:1px solid #bbb;padding:8px 12px;vertical-align:top}"
            ".vlst-lb thead th{position:sticky;top:0;background:#dbeafe;z-index:3;text-align:left}"
            ".vlst-lb td:first-child,.vlst-lb th:first-child{font-weight:700;background:#eef;"
            "position:sticky;left:0;z-index:2;box-shadow:2px 0 4px rgba(0,0,0,.06)}"
            "</style>"
        )
        _h_sum = _sum_df.to_html(index=False, escape=True)
        _h_full = _full_df.to_html(index=False, escape=True)
        _ipy_disp_lb(
            HTML(
                _css
                + "<h4 style=\"margin:8px 0 4px;font-size:16px\">Section 9b — Learned blends</h4>"
                + "<p style=\"margin:4px 0 10px;font-size:15px\">Tables use normal text size; scroll horizontally if columns do not fit. "
                + "Summary first, then full metrics.</p>"
                + "<div class=\"vlst-lb vlst-lb-x\"><div style=\"font-weight:600;margin-bottom:6px\">Summary</div>"
                + _h_sum
                + "</div>"
                + "<div class=\"vlst-lb vlst-lb-x\"><div style=\"font-weight:600;margin-bottom:6px\">Full metrics</div>"
                + _h_full
                + "</div>"
            )
        )
    except Exception as _e_lb:
        print("Scrollable HTML table skipped:", repr(_e_lb))
        print(_sum_df.to_string(index=False))
        print(_full_df.to_string(index=False))

    _lcsv = os.path.join(RESULT_DIR, "learned_blend_metrics.csv")
    LEARNED_BLEND_METRICS_DF.to_csv(_lcsv, index=False)
    print("\nSaved CSV:", _lcsv)

    # --- Merge learned rows into ensemble_blend_comparison (same schema + optional w_lgb, w_lr) ---
    if "blend_table" in globals():
        bt = blend_table.copy()
        for c in ("w_lgb", "w_lr"):
            if c not in bt.columns:
                bt[c] = np.nan
        extras = []
        sw = _wide_vec_to_weight_slots(w_pr, wide_names)
        extras.append(
            _blend_extra_row(
                "learned_wide_pr_auc_on_cal",
                p_cal_learned_wide_pr,
                p_test_learned_wide_pr,
                sw["w_cat"],
                sw["w_xgb"],
                sw["w_rf"],
                sw["w_tabpfn"],
                sw["w_lgb"],
                sw["w_lr"],
            )
        )
        if w_bce is not None and p_cal_learned_wide_bce is not None:
            swb = _wide_vec_to_weight_slots(w_bce, wide_names)
            extras.append(
                _blend_extra_row(
                    "learned_wide_bce_softmax_on_cal",
                    p_cal_learned_wide_bce,
                    p_test_learned_wide_bce,
                    swb["w_cat"],
                    swb["w_xgb"],
                    swb["w_rf"],
                    swb["w_tabpfn"],
                    swb["w_lgb"],
                    swb["w_lr"],
                )
            )
        if (
            globals().get("p_cal_learned4_pr") is not None
            and globals().get("p_test_learned4_pr") is not None
            and globals().get("LEARNED_FOURWAY_BLEND_WEIGHTS_PR_AUC") is not None
        ):
            _d4 = LEARNED_FOURWAY_BLEND_WEIGHTS_PR_AUC
            w4v = np.array(
                [_d4["cat"], _d4["xgb"], _d4["rf"], _d4["tabpfn"]],
                dtype=float,
            )
            if "row_variant_4" in globals():
                extras.append(row_variant_4("learned_fourway_pr_auc_on_cal", w4v))
            else:
                extras.append(
                    _blend_extra_row(
                        "learned_fourway_pr_auc_on_cal",
                        p_cal_learned4_pr,
                        p_test_learned4_pr,
                        float(w4v[0]),
                        float(w4v[1]),
                        float(w4v[2]),
                        float(w4v[3]),
                    )
                )
        if "P_cal" in globals() and p_cal_learned3_pr is not None:
            extras.append(
                _blend_extra_row(
                    "learned_3way_pr_auc_on_cal",
                    p_cal_learned3_pr,
                    p_test_learned3_pr,
                    wd3["cat"],
                    wd3["xgb"],
                    wd3["rf"],
                    float("nan"),
                )
            )

        blend_table_merged = pd.concat([bt, pd.DataFrame(extras)], ignore_index=True)
        _blend_out = os.path.join(RESULT_DIR, "ensemble_blend_comparison.csv")
        blend_table_merged.to_csv(_blend_out, index=False)
        blend_table = blend_table_merged
        print(
            "Updated",
            _blend_out,
            "with learned rows (optional w_lgb / w_lr for wide blends). Re-run section 9c for the TabPFN-only comparison table.",
        )
    else:
        print("(blend_table missing; section 9 not run — ensemble CSV not updated.)")

Wide stack columns: ['Cat_cal', 'XGB_cal', 'RF_cal', 'LGB_cal', 'LR_cal', 'TabPFN_cal'] | shape cal (1223, 6)

=== Learned wide convex (max PR-AUC on cal; softmax + L-BFGS + DE) ===
Threshold-free | PR-AUC cal 1.0 | test 0.6086 | ROC cal 1.0 | ROC test 0.9551
@cal t=0.50  | prec 1.0000 | rec 1.0000 | f1 1.0000 | acc 1.0000
@cal t=0.420 (F1-max on cal) | prec 1.0000 | rec 1.0000 | f1 1.0000 | acc 1.0000
@test t=0.50  | prec 1.0000 | rec 0.0556 | f1 0.1053 | acc 0.9836
@test t=0.420 (F1-max on cal) | prec 1.0000 | rec 0.1667 | f1 0.2857 | acc 0.9855
(F1-max threshold is searched on cal only; same t on cal and test lines.)
weights: {'Cat_cal': 0.0011, 'XGB_cal': 0.0054, 'RF_cal': 0.0213, 'LGB_cal': 0.3714, 'LR_cal': 0.0331, 'TabPFN_cal': 0.5677}

=== Learned wide (PyTorch Adam, softmax, minimize BCE on cal — not PR-AUC objective) ===
Threshold-free | PR-AUC cal 1.0 | test 0.7321 | ROC cal 1.0 | ROC test 0.9841
@cal t=0.50  | prec 1.0000 | rec 1.0000 | f1 1.0000 | acc 1.0000
@cal t=0.050 (F1-max on cal) | prec 1.0000 | rec 1.0000 | f1 1.0000 | acc 1.0000
@test t=0.50  | prec 1.0000 | rec 0.0556 | f1 0.1053 | acc 0.9836
@test t=0.050 (F1-max on cal) | prec 0.8000 | rec 0.2222 | f1 0.3478 | acc 0.9855
(F1-max threshold is searched on cal only; same t on cal and test lines.)
weights: {'Cat_cal': 0.00019999999494757503, 'XGB_cal': 9.999999747378752e-05, 'RF_cal': 0.00019999999494757503, 'LGB_cal': 9.999999747378752e-05, 'LR_cal': 9.999999747378752e-05, 'TabPFN_cal': 0.9993000030517578}

=== Learned 4-model convex on [Cat, XGB, RF, TabPFN] (PR-AUC on cal) ===
Threshold-free | PR-AUC cal 1.0 | test 0.6922 | ROC cal 1.0 | ROC test 0.9804
@cal t=0.50  | prec 1.0000 | rec 1.0000 | f1 1.0000 | acc 1.0000
@cal t=0.280 (F1-max on cal) | prec 1.0000 | rec 1.0000 | f1 1.0000 | acc 1.0000
@test t=0.50  | prec 1.0000 | rec 0.0556 | f1 0.1053 | acc 0.9836
@test t=0.280 (F1-max on cal) | prec 1.0000 | rec 0.2222 | f1 0.3636 | acc 0.9865
(F1-max threshold is searched on cal only; same t on cal and test lines.)
weights: {'cat': 0.17098818114634523, 'xgb': 0.1387099334389274, 'rf': 0.009985019792219864, 'tabpfn': 0.6803168656225067}

=== Learned 3-model blend on section 9 P_cal only (PR-AUC on cal) ===
Threshold-free | PR-AUC cal 0.9998 | test 0.4382 | ROC cal 0.9998 | ROC test 0.9592
@cal t=0.50  | prec 0.9967 | rec 0.9935 | f1 0.9951 | acc 0.9951
@cal t=0.160 (F1-max on cal) | prec 0.9951 | rec 0.9967 | f1 0.9959 | acc 0.9959
@test t=0.50  | prec 0.5000 | rec 0.0556 | f1 0.1000 | acc 0.9826
@test t=0.160 (F1-max on cal) | prec 0.6000 | rec 0.3333 | f1 0.4286 | acc 0.9846
(F1-max threshold is searched on cal only; same t on cal and test lines.)
weights: {'cat': 0.0034321468423777575, 'xgb': 0.08425612200652063, 'rf': 0.9123117311511006}

Saved CSV: ../../data/result/modeling_advanced/learned_blend_metrics.csv
Updated ../../data/result/modeling_advanced/ensemble_blend_comparison.csv with learned rows (optional w_lgb / w_lr for wide blends). Re-run section 9c for the TabPFN-only comparison table.

## 9c. TabPFN — comprehensive comparison (single master table)

This section mirrors the **ensemble-style tools** from section 9 on the **four calibrated probabilities** **[Cat, XGB, RF, TabPFN]** (`P_cal_4` / `P_test_4` from section 9 when TabPFN is enabled).

**What the code adds (column `comparison_block`):**

- **`A_objectives`** — Optimizers on the **probability simplex**: **PR-AUC** (softmax + L-BFGS-B + differential evolution, same spirit as 9b), **MSE** to cal labels, **binary log-loss (BCE)**, **Dirichlet random search** for high **F1 on cal** (with a threshold grid), and for high **precision at t = 0.5** on cal.
- **`C_meta_learners`** — Models fit on the four prob columns only: **SGD log-loss with elastic-net**, **Ridge** scores passed through a **sigmoid**, and **HistGradientBoosting** (wrapped in try/except). Section 9 already contributes **logistic stacking** as `four_stacking_lr_on_probs_cal` in the merged `blend_table`.
- **`B_grids_penalties_oof`**, **`B_learned_from_9b`**, **`D_blend_table`** — Rows **re-used from `blend_table`** (after sections 9 and optional 9b): simplex grids, min-weight / diversity / OOF PR winners, learned blends, and hand TabPFN mixes.

**Run order:** 8b → 9 → optional 9b → **this cell**. Saves **`tabpfn_comprehensive_comparison.csv`** and exposes **`TABPFN_COMPREHENSIVE_DF`**. A smaller **`tabpfn_mix_comparison.csv`** is still written for a short curated subset.

In [20]:
# --- Section 9c: TabPFN-inclusive comprehensive comparison (single master table) ---
# Run after sections 9 and 8b (TabPFN). Section 9b optional (adds learned rows to blend_table).
#
# Structure (see markdown above this cell):
#   A — Convex / smooth objectives on the 4-way simplex [Cat, XGB, RF, TabPFN] (cal-only fit)
#   B — Same family as section 9: reuse grid / penalty / OOF winners (already in blend_table)
#   C — Meta-learners on the four probabilities (not only logistic regression)
#   D — Hand diagnostic mixes from blend_table
#   E — Master table = A + C + curated rows from blend_table (TabPFN-involved), deduped by variant

import os
import json

import numpy as np
import pandas as pd
from scipy.optimize import differential_evolution, minimize
from scipy.special import expit

from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.linear_model import Ridge, SGDClassifier
from sklearn.ensemble import HistGradientBoostingClassifier


def _sm(z):
    z = np.asarray(z, dtype=float).ravel()
    z = z - np.max(z)
    e = np.exp(z)
    return e / (np.sum(e) + 1e-15)


def _learn_pr_simplex(P, y, n_restarts=8, seed=42):
    """Maximize PR-AUC on cal; softmax(z) on 4-simplex."""

    def neg(z):
        w = _sm(z)
        p = np.clip((P @ w).ravel(), 1e-12, 1.0 - 1e-12)
        return -float(average_precision_score(np.asarray(y).astype(int).ravel(), p))

    rng = np.random.RandomState(seed)
    best_z, best_v = None, np.inf
    for z0 in [np.zeros(4)] + [rng.standard_normal(4) for _ in range(n_restarts - 1)]:
        r = minimize(neg, z0, method="L-BFGS-B", options={"maxiter": 400, "ftol": 1e-10})
        if r.fun < best_v:
            best_v, best_z = r.fun, r.x

    def _obj(zf):
        return neg(np.asarray(zf, dtype=float))

    de = differential_evolution(_obj, [(-4.0, 4.0)] * 4, seed=seed, maxiter=100, polish=True)
    if de.fun < best_v:
        best_v, best_z = de.fun, de.x
    return _sm(best_z)


def _learn_smooth(P, y, loss_fn, n_restarts=6, seed=43):
    """Minimize loss_fn(P @ sm(z), y) over z."""

    def obj(z):
        w = _sm(z)
        p = np.clip((P @ w).ravel(), 1e-12, 1.0 - 1e-12)
        return float(loss_fn(p, y))

    rng = np.random.RandomState(seed)
    best_z, best_v = None, np.inf
    for z0 in [np.zeros(4)] + [rng.standard_normal(4) for _ in range(n_restarts - 1)]:
        r = minimize(obj, z0, method="L-BFGS-B", options={"maxiter": 400, "ftol": 1e-11})
        if r.fun < best_v:
            best_v, best_z = r.fun, r.x

    de = differential_evolution(
        lambda z: obj(np.asarray(z, dtype=float)),
        [(-4.0, 4.0)] * 4,
        seed=seed + 1,
        maxiter=90,
        polish=True,
    )
    if de.fun < best_v:
        best_v, best_z = de.fun, de.x
    return _sm(best_z)


def _row_blend_schema(
    variant,
    block,
    p_c,
    p_te,
    w4,
    y_cal_arr,
    y_te_arr,
    t_grid,
    w_lgb=np.nan,
    w_lr=np.nan,
    notes="",
):
    """Match section 9 blend_table columns (+ comparison_block, notes)."""
    t_opt = best_threshold_f1_on_cal(y_cal_arr, p_c, t_grid)
    y_hat = (p_te >= t_opt).astype(int)
    y_te_arr = np.asarray(y_te_arr).astype(int).ravel()
    w4 = np.asarray(w4, dtype=float).ravel()
    return {
        "comparison_block": block,
        "variant": variant,
        "w_cat": float(w4[0]) if np.isfinite(w4[0]) else np.nan,
        "w_xgb": float(w4[1]) if np.isfinite(w4[1]) else np.nan,
        "w_rf": float(w4[2]) if np.isfinite(w4[2]) else np.nan,
        "w_tabpfn": float(w4[3]) if np.isfinite(w4[3]) else np.nan,
        "w_lgb": float(w_lgb),
        "w_lr": float(w_lr),
        "pr_auc_cal": float(average_precision_score(y_cal_arr, p_c)),
        "max_f2_cal": float(max_f2_over_thresholds(y_cal_arr, p_c, t_grid)),
        "pr_auc_test": float(average_precision_score(y_te_arr, p_te)),
        "roc_auc_test": float(roc_auc_score(y_te_arr, p_te)),
        "precision": float(precision_score(y_te_arr, y_hat, zero_division=0)),
        "recall": float(recall_score(y_te_arr, y_hat, zero_division=0)),
        "f1_score": float(f1_score(y_te_arr, y_hat, zero_division=0)),
        "accuracy": float(accuracy_score(y_te_arr, y_hat)),
        "threshold_f1max_cal": float(t_opt),
        "notes": notes or "",
    }


def _random_search_max_f1(P, y, t_grid, n_dir=400, seed=7):
    rng = np.random.RandomState(seed)
    best_f1, best_w, best_t = -1.0, np.ones(4) / 4.0, 0.5
    y = np.asarray(y).astype(int).ravel()
    for _ in range(n_dir):
        w = rng.dirichlet(np.ones(4))
        p = blend(P, w)
        for t in t_grid:
            fv = f1_score(y, (p >= t).astype(int), zero_division=0)
            if fv > best_f1:
                best_f1, best_w, best_t = fv, w, float(t)
    return best_w, best_t, float(best_f1)


def _random_search_max_precision_t05(P, y, n_dir=500, seed=11):
    rng = np.random.RandomState(seed)
    best_pr, best_w = -1.0, np.ones(4) / 4.0
    y = np.asarray(y).astype(int).ravel()
    for _ in range(n_dir):
        w = rng.dirichlet(np.ones(4))
        p = blend(P, w)
        y_hat = (p >= 0.5).astype(int)
        pr = precision_score(y, y_hat, zero_division=0)
        if pr > best_pr:
            best_pr, best_w = pr, w
    return best_w, float(best_pr)


def _stack_probs_row(name, block, clf, Pc, Pt, y_cal_arr, y_te_arr, t_grid):
    clf.fit(Pc, y_cal_arr)
    if hasattr(clf, "predict_proba"):
        p_c = clf.predict_proba(Pc)[:, 1]
        p_t = clf.predict_proba(Pt)[:, 1]
    else:
        zc = clf.predict(Pc)
        zt = clf.predict(Pt)
        p_c = expit(zc)
        p_t = expit(zt)
    return _row_blend_schema(
        name,
        block,
        p_c,
        p_t,
        np.full(4, np.nan),
        y_cal_arr,
        y_te_arr,
        t_grid,
    )


TABPFN_COMPREHENSIVE_DF = None

if "blend_table" not in globals():
    print("Run section 9 first (blend_table).")
elif not globals().get("TABPFN_BLEND_AVAILABLE", False):
    print("TabPFN four-way blends are off (run section 8b; TABPFN_BLEND_AVAILABLE).")
elif globals().get("P_cal_4") is None or globals().get("P_test_4") is None:
    print("P_cal_4 / P_test_4 missing; run section 9 with TabPFN enabled.")
else:
    Pc = np.asarray(P_cal_4, dtype=float)
    Pt = np.asarray(P_test_4, dtype=float)
    yc = np.asarray(y_cal).astype(int).ravel()
    ye = np.asarray(y_test).astype(int).ravel()
    tg = t_grid_blend

    built = []

    # ----- A: objectives on 4-simplex -----
    w_pr = _learn_pr_simplex(Pc, yc, n_restarts=8, seed=42)
    built.append(
        _row_blend_schema(
            "A_opt_fourway_pr_auc_softmax_cal",
            "A_objectives",
            blend(Pc, w_pr),
            blend(Pt, w_pr),
            w_pr,
            yc,
            ye,
            tg,
        )
    )

    w_mse = _learn_smooth(
        Pc,
        yc,
        lambda p, y: np.mean((np.asarray(p).ravel() - np.asarray(y, dtype=float).ravel()) ** 2),
        seed=44,
    )
    built.append(
        _row_blend_schema(
            "A_opt_fourway_mse_softmax_cal",
            "A_objectives",
            blend(Pc, w_mse),
            blend(Pt, w_mse),
            w_mse,
            yc,
            ye,
            tg,
        )
    )

    def _bce(p, y):
        p = np.clip(np.asarray(p, dtype=float).ravel(), 1e-12, 1.0 - 1e-12)
        y = np.asarray(y, dtype=float).ravel()
        return -float(np.mean(y * np.log(p) + (1.0 - y) * np.log(1.0 - p)))

    w_bce = _learn_smooth(Pc, yc, _bce, seed=45)
    built.append(
        _row_blend_schema(
            "A_opt_fourway_neg_logloss_bce_softmax_cal",
            "A_objectives",
            blend(Pc, w_bce),
            blend(Pt, w_bce),
            w_bce,
            yc,
            ye,
            tg,
        )
    )

    w_f1, t_f1, f1v = _random_search_max_f1(Pc, yc, tg, n_dir=350, seed=46)
    built.append(
        _row_blend_schema(
            "A_search_fourway_max_f1_cal_dirichlet",
            "A_objectives",
            blend(Pc, w_f1),
            blend(Pt, w_f1),
            w_f1,
            yc,
            ye,
            tg,
            notes=json.dumps(
                {"cal_f1_at_best_t": round(f1v, 4), "threshold_used_for_f1_search": t_f1}
            ),
        )
    )

    w_prec, prec_v = _random_search_max_precision_t05(Pc, yc, n_dir=450, seed=47)
    built.append(
        _row_blend_schema(
            "A_search_fourway_max_precision_t0p5_cal_dirichlet",
            "A_objectives",
            blend(Pc, w_prec),
            blend(Pt, w_prec),
            w_prec,
            yc,
            ye,
            tg,
            notes=json.dumps({"cal_precision_at_0.5": round(prec_v, 4)}),
        )
    )

    # ----- C: meta-learners on P4 (weights N/A; leave w_* as NaN) -----
    built.append(
        _stack_probs_row(
            "C_meta_sgd_logloss_elasticnet_on_P4_cal",
            "C_meta_learners",
            SGDClassifier(
                loss="log_loss",
                penalty="elasticnet",
                l1_ratio=0.2,
                alpha=0.02,
                max_iter=2500,
                random_state=42,
                class_weight="balanced",
            ),
            Pc,
            Pt,
            yc,
            ye,
            tg,
        )
    )
    built.append(
        _stack_probs_row(
            "C_meta_ridge_sigmoid_on_P4_cal",
            "C_meta_learners",
            Ridge(alpha=2.0, random_state=42),
            Pc,
            Pt,
            yc,
            ye,
            tg,
        )
    )
    try:
        built.append(
            _stack_probs_row(
                "C_meta_histgb_on_P4_cal",
                "C_meta_learners",
                HistGradientBoostingClassifier(
                    max_depth=2,
                    max_iter=120,
                    learning_rate=0.08,
                    random_state=42,
                    class_weight="balanced",
                ),
                Pc,
                Pt,
                yc,
                ye,
                tg,
            )
        )
    except Exception as _eh:
        print("HistGB meta-learner skipped:", repr(_eh))

    extra_df = pd.DataFrame(built)
    for c in extra_df.columns:
        if c == "notes":
            continue
        if extra_df[c].dtype == object:
            continue
        extra_df[c] = pd.to_numeric(extra_df[c], errors="coerce")

    # ----- E: merge with TabPFN-involved blend_table rows -----
    bt = blend_table.copy()

    _B_PREFIXES = (
        "four_equal",
        "four_grid",
        "four_nocat",
        "four_stacking",
        "tabpfn_only",
        "three_way_",
        "cat_tabpfn",
        "xgb_tabpfn",
        "rf_tabpfn",
        "xgb_rf_tabpfn",
        "cat_xgb_tabpfn",
        "cat_rf_tabpfn",
    )

    def _infer_block(v):
        v = str(v)
        if v.startswith("learned_"):
            return "B_learned_from_9b"
        if v.startswith(_B_PREFIXES):
            return "B_grids_penalties_oof"
        return "D_blend_table"

    bt["comparison_block"] = bt["variant"].map(_infer_block)
    if "notes" not in bt.columns:
        bt["notes"] = ""

    mask_tp = (
        (bt["w_tabpfn"].notna() & (bt["w_tabpfn"] > 1e-8))
        | (bt["variant"].astype(str) == "tabpfn_only_calibrated")
        | (bt["variant"].astype(str).str.startswith("learned_wide"))
        | (bt["variant"].astype(str).str.startswith("learned_fourway"))
    )
    bt_sub = bt.loc[mask_tp].copy()

    keys = set(extra_df["variant"].astype(str))
    bt_sub = bt_sub[~bt_sub["variant"].astype(str).isin(keys)]

    cols_order = [
        "comparison_block",
        "variant",
        "w_cat",
        "w_xgb",
        "w_rf",
        "w_tabpfn",
        "w_lgb",
        "w_lr",
        "pr_auc_cal",
        "max_f2_cal",
        "pr_auc_test",
        "roc_auc_test",
        "precision",
        "recall",
        "f1_score",
        "accuracy",
        "threshold_f1max_cal",
        "notes",
    ]
    for c in cols_order:
        if c not in bt_sub.columns and c != "notes":
            bt_sub[c] = np.nan
    if "notes" not in bt_sub.columns:
        bt_sub["notes"] = ""

    master = pd.concat([extra_df, bt_sub], ignore_index=True, sort=False)

    block_rank = {
        "A_objectives": 0,
        "C_meta_learners": 1,
        "B_learned_from_9b": 2,
        "B_grids_penalties_oof": 3,
        "D_blend_table": 4,
    }
    master["_blk"] = master["comparison_block"].map(lambda x: block_rank.get(str(x), 9))
    master = master.sort_values(["_blk", "pr_auc_test"], ascending=[True, False]).drop(columns=["_blk"])

    TABPFN_COMPREHENSIVE_DF = master[[c for c in cols_order if c in master.columns]]

    _view = TABPFN_COMPREHENSIVE_DF.copy()
    for _c in _view.columns:
        if _view[_c].dtype == object:
            continue
        _view[_c] = _view[_c].astype(float).round(4)

    try:
        from IPython.display import HTML, display as _d9c

        _h = _view.to_html(index=False, escape=True)
        _d9c(
            HTML(
                "<style>"
                ".vlst-tp{font-size:15px;line-height:1.35}"
                ".vlst-tp-x{width:100%;overflow-x:auto;overflow-y:visible;margin:10px 0;padding:8px;"
                "border:1px solid #ccc;background:#fff;box-sizing:border-box}"
                ".vlst-tp table{border-collapse:collapse;font-size:15px;white-space:nowrap}"
                ".vlst-tp th,.vlst-tp td{border:1px solid #bbb;padding:8px 12px;vertical-align:top}"
                ".vlst-tp thead th{position:sticky;top:0;background:#e8f5e9;z-index:3;text-align:left}"
                ".vlst-tp td:first-child,.vlst-tp th:first-child{font-weight:700;background:#f1f8e9;"
                "position:sticky;left:0;z-index:2;box-shadow:2px 0 4px rgba(0,0,0,.05)}"
                "</style>"
                "<h4 style=\"margin:8px 0;font-size:16px\">Section 9c — TabPFN comprehensive master table</h4>"
                "<p style=\"font-size:15px;margin:6px 0\"><b>comparison_block:</b> "
                "<code>A_objectives</code> = softmax / search optimizers on cal; "
                "<code>C_meta_learners</code> = classifiers on the four calibrated probs; "
                "<code>B_grids_penalties_oof</code> / <code>B_learned_from_9b</code> / <code>D_blend_table</code> "
                "= rows from section 9/9b that involve TabPFN. Convex rows show weights on [Cat, XGB, RF, TabPFN]; "
                "meta-learners leave weights blank.</p>"
                "<div class=\"vlst-tp vlst-tp-x\">" + _h + "</div>"
            )
        )
    except Exception as _e:
        print("HTML display skipped:", repr(_e))

    print("\n=== Section 9c — plain text ===\n")
    print(_view.to_string(index=False))

    _out = os.path.join(RESULT_DIR, "tabpfn_comprehensive_comparison.csv")
    TABPFN_COMPREHENSIVE_DF.to_csv(_out, index=False)
    print("\nSaved:", _out)

    try:
        vo = [
            "tabpfn_only_calibrated",
            "four_equal_1/4",
            "learned_fourway_pr_auc_on_cal",
            "four_grid_max_pr_auc_cal",
            "four_stacking_lr_on_probs_cal",
        ]
        k = "four_grid_mean_{}fold_oof_pr_cal".format(int(globals().get("BLEND_CV_FOLDS", 5)))
        if k not in vo:
            vo.insert(3, k)
        present = [v for v in vo if v in set(TABPFN_COMPREHENSIVE_DF["variant"].astype(str))]
        _legacy = os.path.join(RESULT_DIR, "tabpfn_mix_comparison.csv")
        TABPFN_COMPREHENSIVE_DF[TABPFN_COMPREHENSIVE_DF["variant"].isin(present)].to_csv(
            _legacy, index=False
        )
        print("Also wrote legacy subset:", _legacy)
    except Exception as _e2:
        print("(Legacy tabpfn_mix_comparison export skipped:", repr(_e2), ")")

=== Section 9c — plain text ===

     comparison_block                                           variant  w_cat  w_xgb   w_rf  w_tabpfn  w_lgb   w_lr  pr_auc_cal  max_f2_cal  pr_auc_test  roc_auc_test  precision  recall  f1_score  accuracy  threshold_f1max_cal                                                                         notes
         A_objectives                     A_opt_fourway_mse_softmax_cal 0.0000 0.0000 0.0000    1.0000    NaN    NaN         1.0      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
         A_objectives         A_opt_fourway_neg_logloss_bce_softmax_cal 0.0000 0.0000 0.0000    1.0000    NaN    NaN         1.0      1.0000       0.7423        0.9900     0.8000  0.2222    0.3478    0.9855                 0.05
         A_objectives             A_search_fourway_max_f1_cal_dirichlet 0.0404 0.3929 0.0538    0.5130    NaN    NaN         1.0      1.0000       0.6728        0.9771     1.0000  0.1667    0.2857    0.9855                 0.46 {"cal_f1_at_best_t": 1.0, "threshold_used_for_f1_search": 0.4600000000000001}
         A_objectives A_search_fourway_max_precision_t0p5_cal_dirichlet 0.2911 0.1783 0.1206    0.4100    NaN    NaN         1.0      0.9997       0.6329        0.9744     0.7500  0.3333    0.4615    0.9865                 0.25                                                 {"cal_precision_at_0.5": 1.0}
         A_objectives                  A_opt_fourway_pr_auc_softmax_cal 0.1824 0.0966 0.2121    0.5089    NaN    NaN         1.0      1.0000       0.5913        0.9728     1.0000  0.1111    0.2000    0.9846                 0.39
      C_meta_learners                           C_meta_histgb_on_P4_cal    NaN    NaN    NaN       NaN    NaN    NaN         1.0      1.0000       0.7155        0.9631     0.8333  0.2778    0.4167    0.9865                 0.30
      C_meta_learners                    C_meta_ridge_sigmoid_on_P4_cal    NaN    NaN    NaN       NaN    NaN    NaN         1.0      1.0000       0.6414        0.9784     1.0000  0.1667    0.2857    0.9855                 0.57
      C_meta_learners           C_meta_sgd_logloss_elasticnet_on_P4_cal    NaN    NaN    NaN       NaN    NaN    NaN         1.0      0.9990       0.6008        0.9703     0.7500  0.3333    0.4615    0.9865                 0.19
    B_learned_from_9b                   learned_wide_bce_softmax_on_cal 0.0002 0.0001 0.0002    0.9993 0.0001 0.0001         1.0      1.0000       0.7321        0.9841     0.8000  0.2222    0.3478    0.9855                 0.05
    B_learned_from_9b                     learned_fourway_pr_auc_on_cal 0.1710 0.1387 0.0100    0.6803    NaN    NaN         1.0      1.0000       0.6922        0.9804     1.0000  0.2222    0.3636    0.9865                 0.28
    B_learned_from_9b                        learned_wide_pr_auc_on_cal 0.0011 0.0054 0.0213    0.5677 0.3714 0.0331         1.0      1.0000       0.6086        0.9551     1.0000  0.1667    0.2857    0.9855                 0.42
B_grids_penalties_oof                          four_grid_max_pr_auc_cal 0.0000 0.0000 0.0000    1.0000    NaN    NaN         1.0      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
B_grids_penalties_oof                   four_grid_mean_5fold_oof_pr_cal 0.0000 0.0000 0.0000    1.0000    NaN    NaN         1.0      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
B_grids_penalties_oof                              four_grid_max_f2_cal 0.0000 0.0000 0.0000    1.0000    NaN    NaN         1.0      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
B_grids_penalties_oof                            tabpfn_only_calibrated 0.0000 0.0000 0.0000    1.0000    NaN    NaN         1.0      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
B_grids_penalties_oof                         four_nocat_max_pr_auc_cal 0.0000 0.0000 0.0000    1.0000    NaN    NaN         1.0      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
B_grids_penalties_oof                             four_nocat_max_f2_cal 0.0000 0.0000 0.0000    1.0000    NaN    NaN         1.0      1.0000       0.7425        0.9901     0.8000  0.2222    0.3478    0.9855                 0.05
B_grids_penalties_oof                                  xgb_tabpfn_50_50 0.0000 0.5000 0.0000    0.5000    NaN    NaN         1.0      0.9997       0.6661        0.9752     1.0000  0.2222    0.3636    0.9865                 0.49
B_grids_penalties_oof                       cat_xgb_tabpfn_equal_thirds 0.3333 0.3333 0.0000    0.3333    NaN    NaN         1.0      0.9993       0.6604        0.9703     0.7500  0.3333    0.4615    0.9865                 0.33
B_grids_penalties_oof                                  cat_tabpfn_50_50 0.5000 0.0000 0.0000    0.5000    NaN    NaN         1.0      1.0000       0.6589        0.9687     0.8000  0.2222    0.3478    0.9855                 0.38
B_grids_penalties_oof                       four_grid_max_pr_min_w10pct 0.1000 0.1000 0.1000    0.7000    NaN    NaN         1.0      1.0000       0.6445        0.9784     0.7500  0.1667    0.2727    0.9846                 0.25
B_grids_penalties_oof                                    four_equal_1/4 0.2500 0.2500 0.2500    0.2500    NaN    NaN         1.0      0.9990       0.5977        0.9694     0.7500  0.3333    0.4615    0.9865                 0.25
B_grids_penalties_oof                     four_grid_pr_minus_0.08x_maxw 0.2000 0.2000 0.3000    0.3000    NaN    NaN         1.0      0.9997       0.5772        0.9681     0.7500  0.3333    0.4615    0.9865                 0.28
B_grids_penalties_oof                     cat_tabpfn_rf_thirds_xgb_tail 0.3000 0.1000 0.3000    0.3000    NaN    NaN         1.0      0.9997       0.5763        0.9678     0.7500  0.3333    0.4615    0.9865                 0.27
B_grids_penalties_oof                        cat_rf_tabpfn_equal_thirds 0.3333 0.0000 0.3333    0.3333    NaN    NaN         1.0      0.9997       0.5638        0.9670     0.8333  0.2778    0.4167    0.9865                 0.28
B_grids_penalties_oof                        xgb_rf_tabpfn_equal_thirds 0.0000 0.3333 0.3333    0.3333    NaN    NaN         1.0      0.9993       0.5566        0.9682     0.8571  0.3333    0.4800    0.9875                 0.32
B_grids_penalties_oof                                   rf_tabpfn_50_50 0.0000 0.0000 0.5000    0.5000    NaN    NaN         1.0      1.0000       0.4891        0.9671     1.0000  0.1111    0.2000    0.9846                 0.41
B_grids_penalties_oof             three_way_pr_winner_plus_tabpfn_25pct 0.0000 0.0750 0.6750    0.2500    NaN    NaN         1.0      0.9993       0.4785        0.9638     0.7500  0.3333    0.4615    0.9865                 0.19
B_grids_penalties_oof             three_way_f2_winner_plus_tabpfn_25pct 0.0000 0.0375 0.7125    0.2500    NaN    NaN         1.0      0.9993       0.4526        0.9631     0.7500  0.3333    0.4615    0.9865                 0.18
B_grids_penalties_oof             three_way_pr_winner_plus_tabpfn_15pct 0.0000 0.0850 0.7650    0.1500    NaN    NaN         1.0      0.9990       0.4499        0.9610     0.6000  0.3333    0.4286    0.9846                 0.14
B_grids_penalties_oof             three_way_f2_winner_plus_tabpfn_15pct 0.0000 0.0425 0.8075    0.1500    NaN    NaN         1.0      0.9990       0.4408        0.9606     0.6667  0.3333    0.4444    0.9855                 0.14

Saved: ../../data/result/modeling_advanced/tabpfn_comprehensive_comparison.csv
Also wrote legacy subset: ../../data/result/modeling_advanced/tabpfn_mix_comparison.csv

In [21]:
# --- After §9c (or standalone): per-block precision winners + one equal mix ---
# Requires: §9 (blend, P_cal_4, P_test_4, y_cal, y_test, t_grid_blend, blend_table, TABPFN_BLEND_AVAILABLE)
# Optional: TABPFN_COMPREHENSIVE_DF (if missing, uses TabPFN rows from blend_table + recomputes A/C probs)
#
# Selection: within each comparison_block, pick the variant with highest PRECISION on cal,
#            searching thresholds on t_grid_blend (no F2).
# Mix: equal average of winners' test (and cal) probabilities; final threshold on cal again maximizes precision.

import json
import numpy as np
import pandas as pd
from scipy.optimize import differential_evolution, minimize
from scipy.special import expit
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.linear_model import Ridge, SGDClassifier
from sklearn.ensemble import HistGradientBoostingClassifier


def _sm(z):
    z = np.asarray(z, dtype=float).ravel()
    z = z - np.max(z)
    e = np.exp(z)
    return e / (np.sum(e) + 1e-15)


def _best_precision_threshold(y_true, p, t_grid):
    """Return (t_best, precision_cal) maximizing precision on y_true (cal)."""
    y_true = np.asarray(y_true).astype(int).ravel()
    p = np.asarray(p, dtype=float).ravel()
    best_t, best_pr = 0.5, -1.0
    for t in t_grid:
        y_hat = (p >= float(t)).astype(int)
        pr = precision_score(y_true, y_hat, zero_division=0)
        if pr > best_pr:
            best_pr, best_t = pr, float(t)
    return best_t, float(best_pr)


def _metrics_at_t(y_true, p, t):
    y_true = np.asarray(y_true).astype(int).ravel()
    p = np.asarray(p, dtype=float).ravel()
    y_hat = (p >= float(t)).astype(int)
    return {
        "precision": float(precision_score(y_true, y_hat, zero_division=0)),
        "recall": float(recall_score(y_true, y_hat, zero_division=0)),
        "f1": float(f1_score(y_true, y_hat, zero_division=0)),
        "accuracy": float(accuracy_score(y_true, y_hat)),
    }


def _learn_pr_simplex(P, y, n_restarts=8, seed=42):
    def neg(z):
        w = _sm(z)
        pv = np.clip((P @ w).ravel(), 1e-12, 1.0 - 1e-12)
        return -float(average_precision_score(np.asarray(y).astype(int).ravel(), pv))

    rng = np.random.RandomState(seed)
    best_z, best_v = None, np.inf
    for z0 in [np.zeros(4)] + [rng.standard_normal(4) for _ in range(n_restarts - 1)]:
        r = minimize(neg, z0, method="L-BFGS-B", options={"maxiter": 400, "ftol": 1e-10})
        if r.fun < best_v:
            best_v, best_z = r.fun, r.x

    def _obj(zf):
        return neg(np.asarray(zf, dtype=float))

    de = differential_evolution(_obj, [(-4.0, 4.0)] * 4, seed=seed, maxiter=100, polish=True)
    if de.fun < best_v:
        best_v, best_z = de.fun, de.x
    return _sm(best_z)


def _learn_smooth(P, y, loss_fn, n_restarts=6, seed=43):
    def obj(z):
        w = _sm(z)
        p = np.clip((P @ w).ravel(), 1e-12, 1.0 - 1e-12)
        return float(loss_fn(p, y))

    rng = np.random.RandomState(seed)
    best_z, best_v = None, np.inf
    for z0 in [np.zeros(4)] + [rng.standard_normal(4) for _ in range(n_restarts - 1)]:
        r = minimize(obj, z0, method="L-BFGS-B", options={"maxiter": 400, "ftol": 1e-11})
        if r.fun < best_v:
            best_v, best_z = r.fun, r.x
    de = differential_evolution(
        lambda z: obj(np.asarray(z, dtype=float)),
        [(-4.0, 4.0)] * 4,
        seed=seed + 1,
        maxiter=90,
        polish=True,
    )
    if de.fun < best_v:
        best_v, best_z = de.fun, de.x
    return _sm(best_z)


def _bce_loss(p, y):
    p = np.clip(np.asarray(p, dtype=float).ravel(), 1e-12, 1.0 - 1e-12)
    y = np.asarray(y, dtype=float).ravel()
    return -float(np.mean(y * np.log(p) + (1.0 - y) * np.log(1.0 - p)))


def _stack_p4(clf, Pc, Pt, y_cal_arr):
    clf.fit(Pc, y_cal_arr)
    if hasattr(clf, "predict_proba"):
        return clf.predict_proba(Pc)[:, 1], clf.predict_proba(Pt)[:, 1]
    zc, zt = clf.predict(Pc), clf.predict(Pt)
    return expit(zc), expit(zt)


TABPFN_PRECISION_BLOCK_WINNERS = None
TABPFN_PRECISION_EQUAL_MIX = None

if not globals().get("TABPFN_BLEND_AVAILABLE"):
    print("TabPFN off — skip precision-mix cell.")
elif globals().get("P_cal_4") is None:
    print("Run section 9 first (P_cal_4).")
else:
    Pc = np.asarray(P_cal_4, dtype=float)
    Pt = np.asarray(P_test_4, dtype=float)
    yc = np.asarray(y_cal).astype(int).ravel()
    ye = np.asarray(y_test).astype(int).ravel()
    tg = t_grid_blend

    catalog = {}

    # --- Rebuild fixed A / C variants (same spirit as §9c; selection here is precision-based) ---
    w_pr = _learn_pr_simplex(Pc, yc, seed=42)
    catalog["A_opt_fourway_pr_auc_softmax_cal"] = (blend(Pc, w_pr), blend(Pt, w_pr))
    w_mse = _learn_smooth(
        Pc,
        yc,
        lambda p, y: np.mean((np.asarray(p).ravel() - np.asarray(y, dtype=float).ravel()) ** 2),
        seed=44,
    )
    catalog["A_opt_fourway_mse_softmax_cal"] = (blend(Pc, w_mse), blend(Pt, w_mse))
    w_bce = _learn_smooth(Pc, yc, _bce_loss, seed=45)
    catalog["A_opt_fourway_neg_logloss_bce_softmax_cal"] = (blend(Pc, w_bce), blend(Pt, w_bce))

    rngp = np.random.RandomState(47)
    best_pr, best_w = -1.0, np.ones(4) / 4.0
    for _ in range(450):
        w = rngp.dirichlet(np.ones(4))
        p = blend(Pc, w)
        y_hat = (p >= 0.5).astype(int)
        pr = precision_score(yc, y_hat, zero_division=0)
        if pr > best_pr:
            best_pr, best_w = pr, w
    catalog["A_search_fourway_max_precision_t0p5_cal_dirichlet"] = (
        blend(Pc, best_w),
        blend(Pt, best_w),
    )

    catalog["C_meta_sgd_logloss_elasticnet_on_P4_cal"] = _stack_p4(
        SGDClassifier(
            loss="log_loss",
            penalty="elasticnet",
            l1_ratio=0.2,
            alpha=0.02,
            max_iter=2500,
            random_state=42,
            class_weight="balanced",
        ),
        Pc,
        Pt,
        yc,
    )
    catalog["C_meta_ridge_sigmoid_on_P4_cal"] = _stack_p4(Ridge(alpha=2.0, random_state=42), Pc, Pt, yc)
    try:
        catalog["C_meta_histgb_on_P4_cal"] = _stack_p4(
            HistGradientBoostingClassifier(
                max_depth=2,
                max_iter=120,
                learning_rate=0.08,
                random_state=42,
                class_weight="balanced",
            ),
            Pc,
            Pt,
            yc,
        )
    except Exception as _e:
        print("HistGB skipped in catalog:", repr(_e))

    # --- All TabPFN-involved rows from blend_table (weights → convex blend) ---
    bt = blend_table.copy()
    mask_tp = (
        (bt["w_tabpfn"].notna() & (bt["w_tabpfn"] > 1e-8))
        | (bt["variant"].astype(str) == "tabpfn_only_calibrated")
        | (bt["variant"].astype(str).str.startswith("learned_wide"))
        | (bt["variant"].astype(str).str.startswith("learned_fourway"))
    )
    for _, row in bt.loc[mask_tp].iterrows():
        vn = str(row["variant"])
        if vn in catalog:
            continue
        wc = row.get("w_cat", np.nan)
        wx = row.get("w_xgb", np.nan)
        wrf = row.get("w_rf", np.nan)
        wt = row.get("w_tabpfn", np.nan)
        if not all(np.isfinite([wc, wx, wrf, wt])):
            continue
        w4 = np.array([float(wc), float(wx), float(wrf), float(wt)], dtype=float)
        if w4.sum() <= 0:
            continue
        catalog[vn] = (blend(Pc, w4), blend(Pt, w4))

    _B_PREFIXES = (
        "four_equal",
        "four_grid",
        "four_nocat",
        "four_stacking",
        "tabpfn_only",
        "three_way_",
        "cat_tabpfn",
        "xgb_tabpfn",
        "rf_tabpfn",
        "xgb_rf_tabpfn",
        "cat_xgb_tabpfn",
        "cat_rf_tabpfn",
    )

    def _infer_block(v):
        v = str(v)
        if v.startswith("learned_"):
            return "B_learned_from_9b"
        if v.startswith("A_opt") or v.startswith("A_search"):
            return "A_objectives"
        if v.startswith("C_meta"):
            return "C_meta_learners"
        if v.startswith(_B_PREFIXES):
            return "B_grids_penalties_oof"
        return "D_blend_table"

    # --- Per block: max precision on cal (best threshold on cal) ---
    rows = []
    by_block = {}
    for vn, (pc, pte) in catalog.items():
        blk = _infer_block(vn)
        t_star, pr_cal = _best_precision_threshold(yc, pc, tg)
        by_block.setdefault(blk, []).append((vn, pr_cal, t_star, pc, pte))

    winners = {}
    for blk, lst in by_block.items():
        lst.sort(key=lambda x: -x[1])
        vn, pr_cal, t_star, pc, pte = lst[0]
        winners[blk] = {
            "variant": vn,
            "block": blk,
            "precision_cal_at_best_t": round(pr_cal, 4),
            "threshold_max_precision_cal": round(t_star, 4),
            "pr_auc_cal": round(float(average_precision_score(yc, pc)), 4),
            "pr_auc_test": round(float(average_precision_score(ye, pte)), 4),
        }
        m_te = _metrics_at_t(ye, pte, t_star)
        rows.append(
            {
                "block": blk,
                "winner_variant": vn,
                "precision_cal": round(pr_cal, 4),
                "threshold_cal": round(t_star, 4),
                "precision_test@that_t": round(m_te["precision"], 4),
                "recall_test@that_t": round(m_te["recall"], 4),
                "f1_test@that_t": round(m_te["f1"], 4),
            }
        )

    win_df = pd.DataFrame(rows).sort_values("block")
    print("\n=== Per-block winner (max precision on cal; threshold grid on cal) ===\n")
    print(win_df.to_string(index=False))

    # --- Equal mix of winner probabilities ---
    p_cal_list = [catalog[winners[b]["variant"]][0] for b in sorted(winners.keys())]
    p_te_list = [catalog[winners[b]["variant"]][1] for b in sorted(winners.keys())]
    p_cal_mix = np.mean(np.stack(p_cal_list, axis=0), axis=0)
    p_te_mix = np.mean(np.stack(p_te_list, axis=0), axis=0)

    t_mix, pr_mix_cal = _best_precision_threshold(yc, p_cal_mix, tg)
    m_cal_mix = _metrics_at_t(yc, p_cal_mix, t_mix)
    m_te_mix = _metrics_at_t(ye, p_te_mix, t_mix)

    TABPFN_PRECISION_BLOCK_WINNERS = winners
    TABPFN_PRECISION_EQUAL_MIX = {
        "blocks_mixed": sorted(winners.keys()),
        "variants_mixed": [winners[b]["variant"] for b in sorted(winners.keys())],
        "threshold_max_precision_cal": t_mix,
        "precision_cal": pr_mix_cal,
        "metrics_cal@t": m_cal_mix,
        "metrics_test@t": m_te_mix,
        "roc_auc_test": float(roc_auc_score(ye, p_te_mix)),
        "pr_auc_test": float(average_precision_score(ye, p_te_mix)),
    }

    print("\n=== Equal mix of per-block precision winners ===")
    print("Blocks:", TABPFN_PRECISION_EQUAL_MIX["blocks_mixed"])
    print("Variants:", TABPFN_PRECISION_EQUAL_MIX["variants_mixed"])
    print("Threshold (max precision on cal):", round(t_mix, 4))
    print("Cal @t:", json.dumps({k: round(v, 4) for k, v in m_cal_mix.items()}))
    print("Test @t:", json.dumps({k: round(v, 4) for k, v in m_te_mix.items()}))
    print("Test PR-AUC:", round(TABPFN_PRECISION_EQUAL_MIX["pr_auc_test"], 4), "| ROC-AUC:", round(TABPFN_PRECISION_EQUAL_MIX["roc_auc_test"], 4))

=== Per-block winner (max precision on cal; threshold grid on cal) ===

                block                          winner_variant  precision_cal  threshold_cal  precision_test@that_t  recall_test@that_t  f1_test@that_t
         A_objectives        A_opt_fourway_pr_auc_softmax_cal            1.0           0.39                    1.0              0.1111          0.2000
B_grids_penalties_oof                          four_equal_1/4            1.0           0.61                    1.0              0.1111          0.2000
    B_learned_from_9b              learned_wide_pr_auc_on_cal            1.0           0.05                    0.8              0.2222          0.3478
      C_meta_learners C_meta_sgd_logloss_elasticnet_on_P4_cal            1.0           0.64                    1.0              0.1111          0.2000

=== Equal mix of per-block precision winners ===
Blocks: ['A_objectives', 'B_grids_penalties_oof', 'B_learned_from_9b', 'C_meta_learners']
Variants: ['A_opt_fourway_pr_auc_softmax_cal', 'four_equal_1/4', 'learned_wide_pr_auc_on_cal', 'C_meta_sgd_logloss_elasticnet_on_P4_cal']
Threshold (max precision on cal): 0.42
Cal @t: {"precision": 1.0, "recall": 1.0, "f1": 1.0, "accuracy": 1.0}
Test @t: {"precision": 1.0, "recall": 0.1111, "f1": 0.2, "accuracy": 0.9846}
Test PR-AUC: 0.5991 | ROC-AUC: 0.9739

## 10. Threshold selection on **calibration** data (not test)

Objectives:
- **F2** (β=2): weights recall higher than F1.
- **Recall at precision ≥** a floor (here 0.35; adjust to your clinical floor).
- **Expected cost**: `cost = C_FP * FP + C_FN * FN` (tune weights).

In [22]:
def metrics_at_threshold(y_true, p, t):
    y_hat = (p >= t).astype(int)
    return {
        "threshold": t,
        "precision": precision_score(y_true, y_hat, zero_division=0),
        "recall": recall_score(y_true, y_hat, zero_division=0),
        "f1": f1_score(y_true, y_hat, zero_division=0),
        "f2": fbeta_score(y_true, y_hat, beta=2, zero_division=0),
    }


def recall_at_min_precision(y_true, p, p_min=0.35):
    best_r = 0.0
    best_t = 0.5
    for t in np.linspace(0.01, 0.99, 199):
        row = metrics_at_threshold(y_true, p, t)
        if row["precision"] >= p_min:
            if row["recall"] > best_r:
                best_r = row["recall"]
                best_t = t
    return best_t, best_r


def best_cost_threshold(y_true, p, c_fp=1.0, c_fn=10.0):
    """Lower C_FN relative to C_FP if missing a case is worse than a false alarm."""
    best = None
    best_cost = 1e18
    n = len(y_true)
    pos = int(y_true.sum())
    neg = n - pos
    for t in np.linspace(0.01, 0.99, 199):
        y_hat = (p >= t).astype(int)
        fp = int(((y_hat == 1) & (y_true == 0)).sum())
        fn = int(((y_hat == 0) & (y_true == 1)).sum())
        cost = c_fp * fp + c_fn * fn
        if cost < best_cost:
            best_cost = cost
            best = t
    return best, best_cost


thresholds_grid = np.arange(0.05, 0.96, 0.01)
rows = [metrics_at_threshold(y_cal, p_cal, t) for t in thresholds_grid]
threshold_scan_cal = pd.DataFrame(rows)

t_f2 = float(threshold_scan_cal.loc[threshold_scan_cal["f2"].idxmax(), "threshold"])
t_rp, r_at_p = recall_at_min_precision(y_cal, p_cal, p_min=0.35)
t_cost, total_cost = best_cost_threshold(y_cal, p_cal, c_fp=1.0, c_fn=15.0)

print("Chosen on calibration — max F2 threshold:", round(t_f2, 3))
print("Chosen on calibration — recall@P>=0.35: t =", round(t_rp, 3), "recall", round(r_at_p, 3))
print("Chosen on calibration — min cost (C_FP=1,C_FN=15): t =", round(t_cost, 3), "cost", total_cost)

THRESHOLD_DEPLOY = t_f2
print("\nDeploy threshold (edit THRESHOLD_DEPLOY if you prefer another rule):", THRESHOLD_DEPLOY)

Chosen on calibration — max F2 threshold: 0.25
Chosen on calibration — recall@P>=0.35: t = 0.01 recall 1.0
Chosen on calibration — min cost (C_FP=1,C_FN=15): t = 0.248 cost 32.0

Deploy threshold (edit THRESHOLD_DEPLOY if you prefer another rule): 0.25000000000000006

## 11. Test evaluation: 0.5 vs tuned threshold

In [23]:
def report_at_t(name, y_te, p_te, t):
    y_hat = (p_te >= t).astype(int)
    print(f"\n=== {name} @ threshold={t:.3f} ===")
    print(classification_report(y_te, y_hat, digits=3))
    print("ROC-AUC:", round(roc_auc_score(y_te, p_te), 4), "| PR-AUC:", round(average_precision_score(y_te, p_te), 4))


report_at_t(f"Ensemble (deploy={win_name})", y_test, p_test, 0.5)
report_at_t(f"Ensemble (deploy={win_name})", y_test, p_test, THRESHOLD_DEPLOY)

threshold_scan_cal.to_csv(
    os.path.join(RESULT_DIR, "threshold_scan_calibration.csv"), index=False
)
summary = pd.DataFrame(
    [
        {
            "rule": "max_F2_on_cal",
            "threshold": t_f2,
            "note": "deploy default",
        },
        {
            "rule": "recall_at_precision_ge_0.35",
            "threshold": t_rp,
            "max_recall_under_constraint": r_at_p,
        },
        {
            "rule": "min_cost_fp1_fn15",
            "threshold": t_cost,
            "total_cost_on_cal": total_cost,
        },
    ]
)
summary.to_csv(os.path.join(RESULT_DIR, "threshold_rules_summary.csv"), index=False)
print("\nSaved:", RESULT_DIR)

=== Ensemble (deploy=grid_max_pr_auc_cal) @ threshold=0.500 ===
              precision    recall  f1-score   support

           0      0.984     0.999     0.991      1019
           1      0.500     0.056     0.100        18

    accuracy                          0.983      1037
   macro avg      0.742     0.527     0.546      1037
weighted avg      0.975     0.983     0.976      1037

ROC-AUC: 0.9595 | PR-AUC: 0.4415

=== Ensemble (deploy=grid_max_pr_auc_cal) @ threshold=0.250 ===
              precision    recall  f1-score   support

           0      0.987     0.998     0.993      1019
           1      0.714     0.278     0.400        18

    accuracy                          0.986      1037
   macro avg      0.851     0.638     0.696      1037
weighted avg      0.983     0.986     0.982      1037

ROC-AUC: 0.9595 | PR-AUC: 0.4415

Saved: ../../data/result/modeling_advanced

## 12. Quick benchmark: individual calibrated models on test (probabilities)

Columns **precision**, **recall**, **f1**, **accuracy** use **`THRESHOLD_DEPLOY`** from §10 (same rule for every row so the table is comparable). **roc_auc** / **pr_auc** are threshold-free.

In [24]:
def bench_row(name, pt, t_deploy):
    y_hat = (pt >= t_deploy).astype(int)
    return {
        "model": name,
        "roc_auc": roc_auc_score(y_test, pt),
        "pr_auc": average_precision_score(y_test, pt),
        "precision": precision_score(y_test, y_hat, zero_division=0),
        "recall": recall_score(y_test, y_hat, zero_division=0),
        "f1": f1_score(y_test, y_hat, zero_division=0),
        "accuracy": accuracy_score(y_test, y_hat),
        "threshold_deploy": float(t_deploy),
    }


_tdep = float(THRESHOLD_DEPLOY)
rows = []
for name, m in [("LR", best_lr), ("RF_merge", best_rf_merge), ("Cat_cal", cal_cat), ("XGB_cal", cal_xgb), ("LGB", best_lgb)]:
    rows.append(bench_row(name, m.predict_proba(X_test)[:, 1], _tdep))

# Learned convex blends (§9b) — placed next to single models for easy comparison
if globals().get("p_test_learned_wide_pr") is not None:
    rows.append(
        bench_row("Learned_wide_PR_on_cal_blend", p_test_learned_wide_pr, _tdep)
    )
if globals().get("p_test_learned_wide_bce") is not None:
    rows.append(
        bench_row("Learned_wide_BCE_softmax_on_cal", p_test_learned_wide_bce, _tdep)
    )
if globals().get("p_test_learned3_pr") is not None:
    rows.append(
        bench_row("Learned_3way_PR_on_cal_blend", p_test_learned3_pr, _tdep)
    )
rows.append(bench_row("Ensemble_avg_cal", blend(P_test, w_equal), _tdep))
rows.append(bench_row("Ensemble_w_pr_full_cal", blend(P_test, w_ap), _tdep))
rows.append(
    bench_row(
        f"Ensemble_w_pr_constrained_min{int(round(BLEND_MIN_WEIGHT * 100))}pct_cal",
        blend(P_test, w_ap_constrained),
        _tdep,
    )
)
rows.append(
    bench_row(
        f"Ensemble_w_pr_divpen_{BLEND_DIVERSITY_LAMBDA:g}_cal",
        blend(P_test, w_div),
        _tdep,
    )
)
rows.append(
    bench_row(
        f"Ensemble_w_mean{BLEND_CV_FOLDS}fold_oof_pr_cal",
        blend(P_test, w_cv),
        _tdep,
    )
)
rows.append(bench_row("Ensemble_w_f2_full_cal", blend(P_test, w_f2), _tdep))
rows.append(bench_row("Ensemble_nocat_w_pr_cal", blend(P_test, w_nocat_ap), _tdep))
rows.append(bench_row("Ensemble_nocat_w_f2_cal", blend(P_test, w_nocat_f2), _tdep))
rows.append(bench_row("Ensemble_stacking_lr_cal", p_test_stack, _tdep))
rows.append(bench_row("Ensemble_used_in_sec10_11", p_test, _tdep))
_tabpfn_bench_ok = (
    globals().get("TABPFN_BLEND_AVAILABLE", False)
    and globals().get("p_tabpfn_test") is not None
    and globals().get("w4_equal") is not None
    and globals().get("P_test_4") is not None
)
if _tabpfn_bench_ok:
    rows.append(bench_row("TabPFN_cal", p_tabpfn_test, _tdep))
if globals().get("p_test_learned4_pr") is not None:
    rows.append(
        bench_row("Learned_fourway_PR_on_cal_blend", p_test_learned4_pr, _tdep)
    )
    rows.append(bench_row("four_equal_1/4_tabpfn_mix", blend(P_test_4, w4_equal), _tdep))
    rows.append(bench_row("four_grid_max_pr_auc_cal", blend(P_test_4, w_ap4), _tdep))
    rows.append(
        bench_row(
            f"four_grid_pr_divpen_{BLEND_DIVERSITY_LAMBDA:g}_cal",
            blend(P_test_4, w_div4),
            _tdep,
        )
    )
    rows.append(
        bench_row("four_nocat_max_pr_auc_cal", blend(P_test_4, w_nocat_ap4), _tdep)
    )
    rows.append(bench_row("four_nocat_max_f2_cal", blend(P_test_4, w_nocat_f24), _tdep))
    rows.append(
        bench_row("cat_tabpfn_50_50", blend(P_test_4, np.array([0.5, 0.0, 0.0, 0.5])), _tdep)
    )
    rows.append(
        bench_row(
            "xgb_rf_tabpfn_equal_thirds",
            blend(
                P_test_4,
                np.array([0.0, 1.0 / 3, 1.0 / 3, 1.0 / 3]),
            ),
            _tdep,
        )
    )
    rows.append(
        bench_row(
            "three_way_pr_winner_plus_tabpfn_15pct",
            blend(
                P_test_4,
                np.array(
                    [0.85 * w_ap[0], 0.85 * w_ap[1], 0.85 * w_ap[2], 0.15]
                ),
            ),
            _tdep,
        )
    )
    rows.append(
        bench_row(
            "three_way_f2_winner_plus_tabpfn_15pct",
            blend(
                P_test_4,
                np.array(
                    [0.85 * w_f2[0], 0.85 * w_f2[1], 0.85 * w_f2[2], 0.15]
                ),
            ),
            _tdep,
        )
    )
    rows.append(bench_row("four_stacking_lr_on_probs_cal", p_test_stack4, _tdep))
bench = pd.DataFrame(rows)
_bench_cols = [
    "model",
    "roc_auc",
    "pr_auc",
    "precision",
    "recall",
    "f1",
    "accuracy",
    "threshold_deploy",
]
_bench_view = bench[[c for c in _bench_cols if c in bench.columns]]
try:
    from IPython.display import HTML, display as _ipy_disp

    _bh = _bench_view.to_html(index=False, float_format=lambda x: f"{x:.4f}" if isinstance(x, (float, np.floating)) else str(x))
    _ipy_disp(
        HTML(
            "<style>.vlst-bwrap{font-size:15px;line-height:1.35}"
            ".vlst-bwrap-x{width:100%;overflow-x:auto;overflow-y:visible;margin:8px 0;padding:8px;border:1px solid #ccc;background:#fff;box-sizing:border-box}"
            ".vlst-bwrap table{border-collapse:collapse;font-size:15px;white-space:nowrap}"
            ".vlst-bwrap th,.vlst-bwrap td{border:1px solid #bbb;padding:8px 12px}"
            ".vlst-bwrap thead th{position:sticky;top:0;background:#dde;z-index:2}"
            ".vlst-bwrap td:first-child{font-weight:600;background:#f3f3f3;position:sticky;left:0;z-index:1}"
            "</style>"
            '<div class="vlst-bwrap"><h4 style="margin:8px 0;font-size:16px">Section 12 — Test benchmark</h4>'
            "<p style=\"font-size:15px;margin:4px 0 8px\">Normal-sized table; scroll horizontally if columns overflow.</p>"
            '<div class="vlst-bwrap vlst-bwrap-x">'
            + _bh
            + "</div></div>"
        )
    )
except Exception as _e_b:
    display(_bench_view)
    print("HTML scroll bench skipped:", repr(_e_b))
print("\n=== Test benchmark (plain text, Kaggle-safe) ===\n")
print(_bench_view.to_string())
bench.to_csv(os.path.join(RESULT_DIR, "test_ranking_metrics.csv"), index=False)

=== Test benchmark (plain text, Kaggle-safe) ===

                                     model   roc_auc    pr_auc  precision    recall        f1  accuracy  threshold_deploy
0                                       LR  0.925962  0.475550   0.120000  0.666667  0.203390  0.909354              0.25
1                                 RF_merge  0.955730  0.412480   0.437500  0.388889  0.411765  0.980714              0.25
2                                  Cat_cal  0.951587  0.608990   0.777778  0.388889  0.518519  0.987464              0.25
3                                  XGB_cal  0.963254  0.598292   0.666667  0.333333  0.444444  0.985535              0.25
4                                      LGB  0.940737  0.597963   0.571429  0.444444  0.500000  0.984571              0.25
5             Learned_wide_PR_on_cal_blend  0.955076  0.608641   0.857143  0.333333  0.480000  0.987464              0.25
6          Learned_wide_BCE_softmax_on_cal  0.984080  0.732131   1.000000  0.055556  0.105263  0.983607              0.25
7             Learned_3way_PR_on_cal_blend  0.959219  0.438174   0.714286  0.277778  0.400000  0.985535              0.25
8                         Ensemble_avg_cal  0.962981  0.578665   0.666667  0.333333  0.444444  0.985535              0.25
9                   Ensemble_w_pr_full_cal  0.959546  0.441479   0.714286  0.277778  0.400000  0.985535              0.25
10  Ensemble_w_pr_constrained_min10pct_cal  0.960855  0.469932   0.750000  0.333333  0.461538  0.986500              0.25
11           Ensemble_w_pr_divpen_0.08_cal  0.962981  0.572285   0.666667  0.333333  0.444444  0.985535              0.25
12         Ensemble_w_mean5fold_oof_pr_cal  0.959546  0.441479   0.714286  0.277778  0.400000  0.985535              0.25
13                  Ensemble_w_f2_full_cal  0.959110  0.432872   0.666667  0.222222  0.333333  0.984571              0.25
14                 Ensemble_nocat_w_pr_cal  0.959546  0.441479   0.714286  0.277778  0.400000  0.985535              0.25
15                 Ensemble_nocat_w_f2_cal  0.959110  0.432872   0.666667  0.222222  0.333333  0.984571              0.25
16                Ensemble_stacking_lr_cal  0.962872  0.577394   0.750000  0.333333  0.461538  0.986500              0.25
17               Ensemble_used_in_sec10_11  0.959546  0.441479   0.714286  0.277778  0.400000  0.985535              0.25
18                              TabPFN_cal  0.990077  0.742476   1.000000  0.055556  0.105263  0.983607              0.25
19         Learned_fourway_PR_on_cal_blend  0.980373  0.692162   0.800000  0.222222  0.347826  0.985535              0.25
20               four_equal_1/4_tabpfn_mix  0.969360  0.597673   0.750000  0.333333  0.461538  0.986500              0.25
21                four_grid_max_pr_auc_cal  0.990077  0.742476   1.000000  0.055556  0.105263  0.983607              0.25
22            four_grid_pr_divpen_0.08_cal  0.968106  0.577216   0.750000  0.333333  0.461538  0.986500              0.25
23               four_nocat_max_pr_auc_cal  0.990077  0.742476   1.000000  0.055556  0.105263  0.983607              0.25
24                   four_nocat_max_f2_cal  0.990077  0.742476   1.000000  0.055556  0.105263  0.983607              0.25
25                        cat_tabpfn_50_50  0.968706  0.658928   0.714286  0.277778  0.400000  0.985535              0.25
26              xgb_rf_tabpfn_equal_thirds  0.968161  0.556584   0.666667  0.333333  0.444444  0.985535              0.25
27   three_way_pr_winner_plus_tabpfn_15pct  0.960964  0.449914   0.666667  0.222222  0.333333  0.984571              0.25
28   three_way_f2_winner_plus_tabpfn_15pct  0.960582  0.440798   0.600000  0.166667  0.260870  0.983607              0.25
29           four_stacking_lr_on_probs_cal  0.971922  0.602351   0.800000  0.222222  0.347826  0.985535              0.25